### ISSUE TITLE
The text "Showing N articles" does not take into account the selected article per page.

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1041]
For example, if 71 articles are total,and I have selected 10 articles per page, the text is shown correctly - Showing article 1-10 out of 71 -
However if I select 20 articles per page, the text still shows 
- showing article 1-10 out of 71
  ![selection_001](https://cloud.githubusercontent.com/assets/1326120/10250958/cd8aadea-68fb-11e5-80af-d86c61c4b90f.png)

**Comment by michaelhidalgo** [comment]
Hmmm, something might have break that feature, it was working before.

Let me take a look

**Comment by romichg** [comment]
Found a little bug with this one. Other than that looks good.

![1041](https://cloud.githubusercontent.com/assets/1326120/10357979/863a9b1c-6d56-11e5-8c33-115f3d457a9f.gif)

**Comment by michaelhidalgo** [comment]
That's interesting : 
When you select the "Check Authorization for All Operations" from left hand side navigation, the number of pages from the dropdown should be set to 2 (since you are seeing 20 records per page and there are 29).

I wonder if there is a js error being thrown in your browser, I gave it a test in a brand new branch and I'm not able to reproduce it.

<img width="1280" alt="screen shot 2015-10-08 at 05 26 19" src="https://cloud.githubusercontent.com/assets/1732035/10365023/36aa2bf4-6d7d-11e5-840c-1bf775c9d574.png">

**Comment by romichg** [comment]
there is no error. I think you need to start with 20 articles per page. Go to index then go to authorization, scroll down and choose page 4. (61-71 articles) then go and click on check authorization

**Comment by romichg** [comment]
this is fixed
