### ISSUE TITLE
In IE 11 Text wraps so that words break in the middle in articles, guides and help

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1055]
![selection_002](https://cloud.githubusercontent.com/assets/1326120/10299131/81d5b410-6bb4-11e5-9923-13a96eb72af4.png)
![selection_003](https://cloud.githubusercontent.com/assets/1326120/10299132/837a9718-6bb4-11e5-9101-7fb8ad3bf148.png)
![selection_004](https://cloud.githubusercontent.com/assets/1326120/10299133/84bcb37c-6bb4-11e5-876e-a08825b91950.png)

**Comment by luchia** [comment]
This has been fixed in my PR today -

![screen shot 2015-10-20 at 12 18 21 pm](https://cloud.githubusercontent.com/assets/4547737/10596181/b1fa31ea-7724-11e5-8b53-10baa86755d5.png)
![screen shot 2015-10-20 at 12 18 25 pm](https://cloud.githubusercontent.com/assets/4547737/10596182/b226160c-7724-11e5-93ec-69f4b58488cd.png)

**Comment by romichg** [comment]
This is fixed.
