### ISSUE TITLE
Scroll bar issues in IE11 and FF on Windows, in article view

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1067]
The vertical scroll bar is not correctly visible. The horizontal scroll bar is present on some articles. Note that this does not happen in Linux on FF, and does not happen in Chrome on Linux or Windows.

![selection_005](https://cloud.githubusercontent.com/assets/1326120/10619885/0a85f2b0-7746-11e5-9fea-1197b7f7d848.png)

this is this article: http://192.168.250.101:12345/angular/user/article/faf4495217b5/Create-a-Threat-Model

![selection_004](https://cloud.githubusercontent.com/assets/1326120/10619887/1153df8a-7746-11e5-8399-5d025b3fc8d5.png)

**Comment by luchia** [comment]
This has been fixed in my PR today -

![screen shot 2015-10-29 at 9 36 48 am](https://cloud.githubusercontent.com/assets/4547737/10805288/afb86dea-7e20-11e5-8bca-47e61e75f906.png)

But, this creates a minor issue in Chrome that I can't get rid of -

![screen shot 2015-10-29 at 9 36 45 am](https://cloud.githubusercontent.com/assets/4547737/10805289/afb89496-7e20-11e5-989c-07ab5e5dd056.png)

**Comment by romichg** [comment]
This is fixed.
