### ISSUE TITLE
Privacy policy is not shown in the menu when you are not logged in

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1105]

**Comment by michaelhidalgo** [comment]
This is an interesting issue that I believe it is caused by the left hand side scroll. Note that the option is there but depending on the browser, the scroll does not shows it up (i.e it does not scroll all the way down)

This is when the browser window is resized: 

<img width="1285" alt="screen shot 2015-11-23 at 07 32 11" src="https://cloud.githubusercontent.com/assets/1732035/11337722/afd853f6-91b4-11e5-9644-aee1287022ab.png">

This is the full window open : 
<img width="1430" alt="screen shot 2015-11-23 at 07 30 53" src="https://cloud.githubusercontent.com/assets/1732035/11337742/f13fcf36-91b4-11e5-91c4-3917f2e0bf32.png">

**Comment by romichg** [comment]
This is fixed.
