### ISSUE TITLE
Implement Password Reset Front end in TM 4.0

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#171]
Right now the password reset email is redirecting to TM 3.5 Backend. We need it to redirect to TM4.0 frontend, provide a pw reset dialogue box and following a successful change redirect back to the TM4.0 login page.

**Comment by luchia** [comment]
Where is this page going to be accessible from seeing as we don't have User pages in Jade?

**Comment by roman87** [comment]
This page is only accessible when the user receives a password reset email and then clicks on the link in that email. All the page needs to contain is the password and confirm password fields.

**Comment by luchia** [comment]
[This has been completed](https://github.com/TeamMentor/TM_4_0_Design/commit/8644b61259c816daef299ca4dd6cb57c925e3473). Michael, I didn't put an action on this one because I wasn't sure where you wanted it to redirect or if you/Dinis had the routing set up already.

![screen shot 2015-01-14 at 4 38 04 pm](https://cloud.githubusercontent.com/assets/4547737/5735069/c04489b6-9c0b-11e4-863c-b8eae2987978.png)

**Comment by michaelhidalgo** [comment]
@roman87, it seems like we need to customize the target URL from the backend, am I wrong?

**Comment by roman87** [comment]
Why is that? We can have the https://localhost:1337/passwordReset/<token> display this form.

**Comment by michaelhidalgo** [comment]
I think the question is how do I fire the email with the link and that the
link points to  https://localhost:1337/passwordReset/ . Because the link is
not accessible from the UI right?

2015-01-14 15:19 GMT-06:00 RomichG <notifications@github.com>:

> Why is that? We can have the https://localhost:1337/passwordReset/
> display this form.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/171#issuecomment-69993966>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by roman87** [comment]
This is done.
