### ISSUE TITLE
Where do we get the 'New Articles' data from?

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#176]
This is needed for https://github.com/TeamMentor/TM_4_0_Design/issues/113

![image](https://cloud.githubusercontent.com/assets/656739/5542886/33b60f0c-8ae4-11e4-84e6-f34b93efc30e.png)

**Comment by michaelhidalgo** [comment]
I started looking at the NGit API:

We will have a single Library (Uno in our case) with all the articles in there. It's required to have the library properly configured in the TM Secret data configuration at Github.

Now by using NGit, I'm able to fetch the latest commits.  In this case below, that single commit contains several files modified, but in theory when an article is created/modified, each commit should reference a single file? Am I wrong?

Now in the other hand, the API returns a byte array (which was converted to clear text) to get the following information : 

If it works, a possible way is to pull the GUIDs from the plain text in order to identify which files were modified.

![screen shot 2015-01-12 at 11 56 59 am](https://cloud.githubusercontent.com/assets/1732035/5707933/7f2ea200-9a52-11e4-8e9b-3277e3e915b1.png)

**Comment by roman87** [comment]
Commit may contain more than one modified article. 

If we pull the guids, then we can add that data to the graphDB. That way we can add the last mod time as an attribute to the article. 
This seems quite complicated for this beta version. I think we should push this functionality to sprint 3. What do you guys @DinisCruz @luchia think?

**Comment by DinisCruz** [comment]
To be honest, I think the 'New Articles' feature will only make sense when there is a constant stream of articles being added to TM, if not, that value is going to be very stale (and we might has well do it manually).

Also I just realised that a better location to get this (in the short term) is the Edit values of the User activity logs

![image](https://cloud.githubusercontent.com/assets/656739/5708802/28fe0f30-9a8c-11e4-8099-6c24360cd433.png)

**Comment by roman87** [comment]
Ok then we agree that we leave it for sprint 3.

**Comment by DinisCruz** [comment]
I think we should close this for now, since it will not happen anytime soon (at least until there is more editing activities and we have access to that edit data)

**Comment by roman87** [comment]
Assigning to myself to story and close

**Comment by romichg** [comment]
Closing
