### ISSUE TITLE
Create one image for all 'customer logos' that are currently used on the home page

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#184]
At the moment we have a number of logos that are downloaded individually, and it will be better for maintainability and updatability if there are all downloaded as one images

![image](https://cloud.githubusercontent.com/assets/656739/5601947/b5ae0308-9321-11e4-8bea-2660f070743b.png)

**Comment by luchia** [comment]
When we have this as a sprite, we have an issue. Because a sprite is a background image, when the columns get smaller, the background image does not. This means the logos are getting cut off as the screen scales.

I tried a couple of different solutions, including making inline images with classes for the sprite, but I could not get this to work. If you have any different suggestions as to how to go about this, please let me know.

**Comment by roman87** [comment]
I actually think it is better to keep the logos as individual images. Simple reason is that we (hopefully) will add customers and logos as a result and we want to make it as easy as possible to do so.

**Comment by DinisCruz** [comment]
ok
