### ISSUE TITLE
Due to NodeJs Express static mapper, TM Design allows download of static files

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#206]
#### Description
Due to the use of express' (web server) static routes  it is possible to download any static files from the current TM_4_0_Design repo, including source code files and 3rd party dependencies 

For example

* http://localhost:1337/package.json
* http://localhost:1337/node_modules/express/package.json
* http://localhost:1337/source/jade/_layouts/head.jade
* http://localhost:1337/node_modules/jade/package.json
* http://localhost:1337/node/server.coffee
* http://localhost:1337/.logs/Mon-Jan-05-2015.log
* http://localhost:1337/.tmCache/docs_cache/json_post_https___docs.teammentor.net_aspx_pages_tm_webservices.asmx_getfolderstructure_libraries

#### Risk Analysis
* So far it looks like none of the files in TM_4_0_Design have any secrets (and the source code is publicly available on GitHub)
* The TM_4_0_GraphDB project does have a secret file (see https://github.com/TeamMentor/TM_4_0_Design/issues/178) but that project (at the moment) does not have the same issue.
* An interesting XSS attack vector would be if one of the npm dependencies used (stored inside node_modules) had an HTML file with an DOM XSS vuln

#### Root Cause

https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/services/Express-Service.coffee#L37-L38
![image](https://cloud.githubusercontent.com/assets/656739/5642726/63225616-9646-11e4-8b3c-1005071657a3.png)

#### References:
* http://expressjs.com/advanced/security-updates.html
* http://blog.nodejs.org/vulnerability/
* http://stackoverflow.com/questions/14612143/node-js-express-framework-security-issues
* https://blog.liftsecurity.io/2012/12/07/writing-secure-express-js-apps
* https://github.com/strongloop/express/issues?q=is%3Aissue+security

----
[TM-4.0-Security](https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security)

**Comment by DinisCruz** [comment]
Note: I created a new Label (called **Type: Security**) that we can use to track these issues

**Comment by DinisCruz** [comment]
require 'fluentnode'

async     = require 'async'
supertest = require 'supertest'

TM_Design_Server = require('../../TM_4_0_Design/node/server')

describe 'security | to-review',->

  describe.only 'Due to NodeJs Express static mapper, TM Design allows download of static files', ->

    it 'using supertest', (done)->
      targets = [
                  { status: 200 ,  path: '/package.json'}
                  { status: 200 ,  path: '/node_modules/jade/package.json'}

                  { status: 404 ,  path: '/aaaaaaa.json'}
                  { status: 200 ,  path: '/guest/about.html'}

                  { status: 404 ,  path: '/node_modules/express/package.json'}      # these don't work via supertest
                  { status: 404 ,  path: '/source/jade/_layouts/head.jade'}         # but work on the
                  { status: 404 ,  path: '/node/server.coffee'}]                    # browser


      server = supertest(TM_Design_Server)

      test_Path= (target, next)->
        server.get(target.path)
              .expect(target.status)
              .end (err,res)->
                if err
                  log res.text
                next()

      async.eachSeries(targets, test_Path, done)

    it 'using http request', (done)->
      qa_Server  = "http://localhost:1337"
      targets    = ['/','/guest/about.html'                              # these should be there

                    '/package.json', '/node_modules/jade/package.json'   # these shouldn't
                    '/node_modules/express/package.json'
                    '/source/jade/_layouts/head.jade'
                    '/node/server.coffee']

      qa_Server.GET (html)->

        (done(); return) if is_Null(html)   # check if the qa_Server is available

        test_Path = (target, next)->
          qa_Server.append(target).GET (html)->
            html.assert_Not_Contains('Cannot GET')
            next()

        async.eachSeries(targets, test_Path, done)

**Comment by DinisCruz** [comment]
There were [directory traversal vulnerabilities in express.static](https://github.com/strongloop/express/issues/2486) fixed in Express 4.8.8

**Comment by dougwilson** [comment]
The issue was introduced here: https://github.com/TeamMentor/TM_4_0_Design/commit/80c910dd0c5c18723a1e976e3896f286841b0941 ; that line should have been only serving the directories that needed to be public, not everything in the entire project.

**Comment by DinisCruz** [comment]
@dougwilson correct (and that code has since been refactored to )

The fix is to only expose these two folders:
* https://github.com/TeamMentor/TM_4_0_Design/tree/master/deploy
* https://github.com/TeamMentor/TM_4_0_Design/tree/master/static (this one still needs the build fix)

**Comment by dougwilson** [comment]
Cool :)

This is what you want to do to limit to those two directories and keep the URLs the same:
```js
app.use('/deploy', express.static(path.join(__dirname, 'deploy')))
app.use('/static', express.static(path.join(__dirname, 'static')))
```
Note that you should _never_ use `process.cwd()` because that is not controlled by your app unless you explicitly set it with `process.chdir()`--I always recommend to provide only absolute paths. `__dirname` contains the absolute path to the directory the script you write that line is located and you can use `path.join` to specify relative from that point (and use `..` if you need to go down).

**Comment by DinisCruz** [comment]
Thanks @dougwilson and on the topic of security, you might find interesting the [routes.test.coffee](https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/tests/routes/routes.test.coffee) test. 

That test represents the (dynamic) attack surface of this application, and creates (dynamically) the 30 mocha tests you can see execute at https://travis-ci.org/TeamMentor/TM_4_0_Design/builds/46178324#L292-L326

The best part is that test will break if there is any new route added to his app, which gives me a great way to control the attack surface (i.e. exposed urls/methods)

**Comment by dougwilson** [comment]
Cool :) I which I could read CoffeeScript, though.

**Comment by DinisCruz** [comment]
@dougwilson sinceCoffee compiles to Javascript, we can use the **try coffeescript** tool at http://coffeescript.org/ to convert to/from Coffee

![image](https://cloud.githubusercontent.com/assets/656739/5649602/1f17043c-968f-11e4-8993-d1d5bedc0d38.png)

Here is what that  [routes.test.coffee](https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/tests/routes/routes.test.coffee) test file looks like in Javascript:

```javascript
var app, supertest;

supertest = require('supertest');

app = require('../../server');

describe('routes | routes.test |', function() {
  var expectedPaths, route, runTest, _i, _len, _results;
  expectedPaths = ['/', '/flare/:area/:page', '/flare/default', '/Image/:name', '/article/view/:guid/:title', '/config', '/dirName', '/flare', '/flare/all', '/flare/main-app-view', '/graph/:queryId', '/graph/:queryId/:filters', '/guest/:page.html', '/help/:page*', '/index.html', '/libraries', '/library/:name', '/library/queries', '/mainModule', '/module', '/ping', '/pwd', '/session', '/test', '/user/login', '/user/login', '/user/logout', '/user/main.html', '/user/pwd_reset', '/user/sign-up', '/version'];
  before(function() {
    return app.server = app.listen();
  });
  after(function() {
    return app.server.close();
  });
  it('Check expected paths', function() {
    var paths, routes;
    paths = [];
    routes = app._router.stack;
    routes.forEach(function(item) {
      if (item.route) {
        return paths.push(item.route.path);
      }
    });
    paths.length.assert_Is(expectedPaths.length);
    return paths.forEach(function(path) {
      return expectedPaths.assert_Contains(path);
    });
  });
  runTest = function(originalPath) {
    var expectedStatus, path, postRequest, testName;
    path = originalPath.replace(':version', 'flare').replace(':area/:page', 'help/index').replace(':page', 'default').replace(':queryId', 'AAAA').replace(':filters', 'BBBB');
    expectedStatus = 200;
    if (['image', 'deploy'].contains(path.split('/').second().lower())) {
      expectedStatus = 302;
    }
    if (['/flare', '/flare/main-app-view', '/user/login', '/user/logout', '/user/sign-up'].contains(path)) {
      expectedStatus = 302;
    }
    if (['article', 'graph', 'library', 'libraries'].contains(path.split('/').second().lower())) {
      expectedStatus = 403;
    }
    if (['/user/main.html'].contains(path)) {
      expectedStatus = 403;
    }
    postRequest = ['/user/pwd_reset', '/user/sign-up'].contains(path);
    testName = ("[" + expectedStatus + "] " + originalPath) + (path !== originalPath ? "  (" + path + ")" : "");
    return it(testName, function(done) {
      var checkResponse;
      checkResponse = function(error, response) {
        assert_Is_Null(error);
        response.text.assert_Is_String();
        return done();
      };
      if (postRequest) {
        return supertest(app).post(path).send({}).expect(expectedStatus, checkResponse);
      } else {
        return supertest(app).get(path).expect(expectedStatus, checkResponse);
      }
    });
  };
  _results = [];
  for (_i = 0, _len = expectedPaths.length; _i < _len; _i++) {
    route = expectedPaths[_i];
    _results.push(runTest(route));
  }
  return _results;
});
```

Its funny that now that I'm so used to coding in coffee-script, I find the coffee code much more readable :)

**Comment by dougwilson** [comment]
> Its funny that now that I'm so used to coding in coffee-script, I find the coffee code much more readable :)

Probably because what you pasted above _is_ less readable, since the tool spits our code suitable for machines, not humans to read (and it lost all your formatting too). I'm not sure what is really happening in the JavaScript you paste, either, lol.

**Comment by dougwilson** [comment]
Though it doesn't look like that test would have helped with the `express.static` usage that this issue is about :(

**Comment by DinisCruz** [comment]
yes, correct, in fact, I found the current issue when I asked my self the question 'I wonder what other paths are there in this app?'

Maybe another technique could be to add a 'global watcher' to express, and capture/log all requests served (the idea would be to build 'file structure like' tree of all pages rendered). What would be nice about that approach, is that that list/tree would represent the 'real' attack surface (as used by users)

**Comment by dougwilson** [comment]
Yea, there are probably modules out there on `npm` that will do this, or you can always make one :) The npm module `morgan` is the "official" access log-style logger for Express, though I'm not sure that meets what you're looking for.

It wouldn't be something added to the express core, through, as the express core is made to only contain the essentials (even containing `express.static` is hotly debated--it is just a reference to the `serve-static` module).

**Comment by dougwilson** [comment]
P.S. if you ever want to talk, share your ideas, etc. I'm always open to having a Skype call or whatever :) Feel free to shoot me an email any time.

**Comment by DinisCruz** [comment]
cool @dougwilson I will remember that :)

Thanks again for the help and comments

**Comment by DinisCruz** [comment]
@dougwilson what is your Skype name? (mine is DinisCruz) I do have another question for you :)

**Comment by dougwilson** [comment]
It's no problem :) I don't really post it out here since people will probably start adding me randomly :) You can always ask me via email, or, since you already posted yours, I'll just add you :)

**Comment by roman87** [comment]
Ideally it is a matter of comparing access log (which we don't have, but should in the TM app) and the known app surface we already have. Technically the issue only arises when the access log shows a successful request for a page that we don't have in our app surface list. That means a successful intrusion. I am not sure if it makes sense to do this in the app since this is much better handled by monitoring tools like Qradar and ArkSight. 

Anyways @DinisCruz  can we close this issue since looks like it has been fixed?

**Comment by DinisCruz** [comment]
I has not been fixed, which you can confirm by the fact that this test still passes: master/tests/security/to-review.coffee#L10

The solution is https://github.com/TeamMentor/TM_4_0_Design/issues/206#issuecomment-69047991 

I will also review http://expressjs.com/guide/using-middleware.html#middleware.built-in and understand better how express-static works

**Comment by DinisCruz** [comment]
For reference the current express implementation allows the enumeration of the server side path that is 'abstracted' by server-static

for example:
 * http://localhost:1332/docs/..%2fswagger-ui/
 * http://localhost:3000/docs/%2f..%2f..%2fmiddleware/swagger-ui/
 * http://localhost:1332/docs/..%2f..%2f..%2f..%2fTM_4_0_GraphDB%2fnode_modules%2fswagger-node-express%2fswagger-ui/

Here is the code that does the check

![image](https://cloud.githubusercontent.com/assets/656739/5797632/c77c315e-9fb5-11e4-9f20-cc72d398bf85.png)

In fact the check actually happens on the ```send``` module

I do find it a bit worrying that express does not normalize the paths as soon as it can, and allows ../.. to exist quite deep in the code

Here is a valid request (http://localhost:1332/docs/..%2f..%2f..%2f..%2fTM_4_0_GraphDB%2fnode_modules%2fswagger-node-express%2fswagger-ui/) , with path disclosure (i.e. works as if the request was http://localhost:1332/docs)

![image](https://cloud.githubusercontent.com/assets/656739/5797680/8bc387d8-9fb6-11e4-82c2-1d19747b71e4.png)

Here is an invalid request: http://localhost:1332/docs/..%2f..%2f..%2f..%2f

![image](https://cloud.githubusercontent.com/assets/656739/5797699/d404417c-9fb6-11e4-81df-1ea2419c5eeb.png)

which is normalized to an parent folder:

![image](https://cloud.githubusercontent.com/assets/656739/5797712/f4d7bc08-9fb6-11e4-999c-a9a031b2b0d7.png)

... and fails (as expected) the check for 'root path'

![image](https://cloud.githubusercontent.com/assets/656739/5797726/24217030-9fb7-11e4-9b26-96161834cbbe.png)

**Comment by dougwilson** [comment]
@DinisCruz so, what you're saying is, you have the root set to the `swagger-ui` folder, so you cannot actually access files outside of it, but you can send a path that goes down and back up, essentially allowed you to determine, from the outside, what that root path is? If so, that definitely sounds like a bug to me and I need to get it fixed.

**Comment by DinisCruz** [comment]
@dougwilson yes that is exactly what is happening

You can see that in action in this url (that works)

```
http://localhost:1332/docs/..%2f..%2f..%2f..%2fTM_4_0_GraphDB%2fnode_modules%2fswagger-node-express%2fswagger-ui/
```

which basically is (with the url bits decoded in bold)

http://localhost:1332/docs/**../../../../**TM_4_0_GraphDB%2fnode_modules%2fswagger-node-express%2fswagger-ui/

My view is that the real bug is that paths like **/..%2f..%2f..%2f..%2** should be resolved asap in express (ideally in a way that no script is exposed to paths with **../..**

**Comment by dougwilson** [comment]
> My view is that the real bug is that paths like /..%2f..%2f..%2f..%2 should be resolved asap in express (ideally in a way that no script is exposed to paths with ../..

Sure, but I can use some example of what to do here. As long as the `/` is encoded as `%2f`, Express itself cannot touch it, otherwise you cannot have URLs like `/find/http:%2F%2Flocalhost%2F/stuff` (i.e. having things like URLs encoded into path parts, probably for proxying stuff).

Otherwise, if the URLs given was `http://localhost:1332/docs/../../../../TM_4_0_GraphDB%2fnode_modules%2fswagger-node-express%2fswagger-ui/`, the best Express itself could do would be to send a permanent redirect to what ti resolves to: `http://localhost:1332/../../../TM_4_0_GraphDB%2fnode_modules%2fswagger-node-express%2fswagger-ui/`.

This is why I'm suggesting the fix is deeper than that; the issue is to not allow the ability to resolve the root path by going down and then trying different path names to go back up. I have to think about this fix a bit, because the modules that this ends up in have a lot of use outside of Express and ideally I can make a fix that's backward-compatible such that you don't have to upgrade to Express 5 to get the fix.

**Comment by DinisCruz** [comment]
I have to say having a URL with ```/find/http:%2F%2Flocalhost%2F/stuff``` is pretty hard-core :) 

And it is bound to create a number of vulnerabilities since (for example) i was under the impression that you couldn't use / in url vars (i.e. you would have to use them in url query or form params). 

Do other web servers/frameworks support that kind of url parameters?

**Comment by dougwilson** [comment]
> Do other web servers/frameworks support that kind of url parameters?

I use Nancy (which is C#) and it absolutely does. I assume every framework allows you to have `%2F`, but I don't have experience using Express (JS), Nancy (C#), Catalyst (Perl), Mojolicious (Perl), Dancer (Perl) and they all have no problem with URL parameters containing forward slashes, since it's part of the URI spec.

**Comment by roman87** [comment]
@joebasirico  maybe someone on your team is interested in joining this discussion.

**Comment by joebasirico** [comment]
I had Dylan, our intern, take a look at this and he wrote this up just now. Hopefully it’s helpful.

Joe

Dylan Says:
So first I think it's important they change the version numbers in package.json from "latest" to the actual version number they use to when I clone the repository and install the dependencies everything doesn't break.

I'm doing this at a glance, I didn't clone the repository and run the server and give it a solid code review pentest, however from the latest express documentation the following is the way you set static assets

app.use(express.static(__dirname + '/public'));

 below is the way it's being done in the app

 @app.use(express['public'](process.cwd()));
now process.cwd() returns the current working directory, so effectively if I'm reading this right, it's just a simple 1 line misconfiguration where instead of setting a public subfolder with static assets, the entire current working directory is being set as static assets.

That said, this information comes with the disclaimer I did not read all the comments in the issue and did not clone and test everything.

**Comment by joebasirico** [comment]
I had Dylan, our intern, take a look at this and he wrote this up just now. Hopefully it’s helpful.

Joe

**Dylan Says:**
So first I think it's important they change the version numbers in package.json from "latest" to the actual version number they use to when I clone the repository and install the dependencies everything doesn't break.

I'm doing this at a glance, I didn't clone the repository and run the server and give it a solid code review pentest, however from the latest express documentation the following is the way you set static assets

`app.use(express.static(__dirname + '/public'));`

below is the way it's being done in the app

`@app.use(express['public'](process.cwd()));`

now process.cwd() returns the current working directory, so effectively if I'm reading this right, it's just a simple 1 line misconfiguration where instead of setting a public subfolder with static assets, the entire current working directory is being set as static assets.

That said, this information comes with the disclaimer I did not read all the comments in the issue and did not clone and test everything.

**Comment by roman87** [comment]
Thanks @joebasirico. Sorry, I should have been more specific. Dylan is right in his suggestion. I am actually wondering about your teams take on comments starting from  https://github.com/TeamMentor/TM_4_0_Design/issues/206#issuecomment-70461414.  Basically the enumeration of actual server root path by going down and up the directory structure through use of ..%2F

**Comment by dxa4481** [comment]
At a glance it looks like what you've said is accurate, and this is a low level vulnerability. I've pinged Douglas Wilson (the point of contact on the express team) and I'll get back to you with what he has to say.

This is not the first low level issue I've found in this space (not the first time I've emailed Douglas), I actually discovered this one over the summer while working on an engagement https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-6394

**Comment by dxa4481** [comment]
Here's the reply

Hi Dylan, this is regarding https://github.com/TeamMentor/TM_4_0_Design/issues/206 right? I believe that it is definitely correct, that it looks like there is an ability to probe what the part of the restricted root directory is from the outside (information disclosure). I'm looking into this and want to have this fixed ASAP :)

I have not, yet, personally verified the disclosure, but from the comments there and looking at the code, I believe the assertion is correct in that it exists.

I'll ping you as soon as I have a fix.

**Comment by dougwilson** [comment]
@dxa4481 ;) ;) ;) I don't mind.

**Comment by dougwilson** [comment]
There is currently a tentative fix for the root path information disclosure discussed in https://github.com/TeamMentor/TM_4_0_Design/issues/206#issuecomment-70461414 (installable as `npm install tj/send`). Thanks to @DinisCruz for the discovery and @dxa4481 for the assist :O!

**Comment by DinisCruz** [comment]
@joebasirico  @dxa4481 (Dylan right?), thanks for the comments

I just opened https://github.com/TeamMentor/TM_4_0_Design/issues/275 and https://github.com/TeamMentor/TM_4_0_Design/issues/276 to track the dependencies issue.

Btw, we're keeping track of all our current security issues (and thinking) on the https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-4.0-Security page, if would be great if you could take a look.

The latest dev versions (and its state) can be seen at: https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-Repos-build-status

Thanks

**Comment by dougwilson** [comment]
For the root directory disclosure vulnerability, I have updated the entire chain with the fix.

Fixed in send 0.11.1
Fixed in serve-static 1.8.1 (because of send dependency update)
Fixed in express 4.11.1 (because of send and serve-static dependencies updates)

**Comment by DinisCruz** [comment]
@dougwilson thanks, I will update our versions too

**Comment by romichg** [comment]
Closing this since this was fixed a while ago.
