### ISSUE TITLE
Improve design of Help page

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#238]
Since @luchia has some design cycles this week, It would be good to improve the design of the help page:

* no clear indication that we are on the HELP page (and top left area fells squished)
* conflict of styles between the title of the page and the help content:

![image](https://cloud.githubusercontent.com/assets/656739/5720559/b6b1b2c8-9b1d-11e4-9777-5f180158471d.png)

and 

![image](https://cloud.githubusercontent.com/assets/656739/5720579/f213bb2c-9b1d-11e4-943e-61168a1b87d9.png)

**Comment by luchia** [comment]
I don't mind the current design because it aligns with TM 4.0 design. I did do some tidying up and have attached screenshots.

![screen shot 2015-01-14 at 10 37 24 am](https://cloud.githubusercontent.com/assets/4547737/5732428/63822d2e-9bdd-11e4-9d67-9f777cd09918.png)
![screen shot 2015-01-14 at 10 39 01 am](https://cloud.githubusercontent.com/assets/4547737/5732429/638aacec-9bdd-11e4-91c7-5eb6c66cc3ba.png)

I have some ideas about how to improve it but it would be moving away from the three column layout which was always going to have a tendency for asymmetry. I did say we would probably have this issue when I first started doing the re-design - I actually wanted something more like [this](https://dribbble.com/shots/829195-Slate/attachments/86422) - but it was decided to stick with a similar layout to 4.0 so that it wasn't such a huge jump from 3.5 (which is a great decision for our users).

It's difficult to design good solutions when you aren't able to use JS at all - it knocks out dropdown buttons, accordions, tabs, off-canvas divs etc - so maybe this could be something we think about for future versions of TM.

**Comment by roman87** [comment]
I think we are fine with this update version for Jade. For Flare we can think of a richer prettier interface.

**Comment by roman87** [comment]
Assigning to myself for testing and closing

**Comment by roman87** [comment]
I don't see the underlines in the latest version.

**Comment by luchia** [comment]
Argh, sorry I must have accidentally deleted that line in the css file. [This has been fixed](https://github.com/TeamMentor/TM_4_0_Design/commit/a43f054b32a1d8f712c8d8ff1b58dba019d4fca4).

![screen shot 2015-01-16 at 11 02 15 am](https://cloud.githubusercontent.com/assets/4547737/5769994/2fda687c-9d6f-11e4-8e57-2b2bc076a10a.png)

**Comment by roman87** [comment]
This is done
