### ISSUE TITLE
Top Menu Navigation Icon gets separated from the word describing it when in smaller size browser

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#257]
![selection_060](https://cloud.githubusercontent.com/assets/1326120/5733608/b002724a-9b73-11e4-8bbb-96580aacb1d6.png)

**Comment by luchia** [comment]
[So I ended up having to make the navigation display: block (display vertically for Mobile)](https://github.com/TeamMentor/TM_4_0_Design/commit/21b58846812241807ce7d7d44dad0315b517834f) because I just couldn't get it to fit in and font size is important on mobile, so we shouldn't go any smaller with it.

I ended up with these solutions - let me know what you think.

![screen shot 2015-01-16 at 11 38 36 am](https://cloud.githubusercontent.com/assets/4547737/5770326/84d60674-9d74-11e4-9f45-e30fa5847147.png)
![screen shot 2015-01-16 at 11 38 40 am](https://cloud.githubusercontent.com/assets/4547737/5770327/84e65d9e-9d74-11e4-8d1c-fb3f7ba13ec5.png)
![screen shot 2015-01-16 at 11 38 45 am](https://cloud.githubusercontent.com/assets/4547737/5770328/84e84d20-9d74-11e4-8702-1448542413b5.png)
![screen shot 2015-01-16 at 11 38 48 am](https://cloud.githubusercontent.com/assets/4547737/5770329/84efc348-9d74-11e4-8849-b3d04b7698fc.png)

**Comment by roman87** [comment]
don't close the issue though :)

**Comment by luchia** [comment]
Woops, sorry!

**Comment by roman87** [comment]
Why do we keep closing this issue :)?

**Comment by romichg** [comment]
fixed.
