### ISSUE TITLE
Add a successful sign-in test to user-account.coffee

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#260]
Here https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/user-account.coffee

**Comment by roman87** [comment]
Lets point out the dofference between this and #246

**Comment by michaelhidalgo** [comment]
For this specific issue, I added new test to validate all the error messages from the backend, for both login and sign up, but I did not add a test to verify that the signup was successful. This test case is the one missing from the sign up workflow because the other validations has been already covered.

**Comment by michaelhidalgo** [comment]
Pull Request here https://github.com/TeamMentor/TM_4_0_QA/pull/5, passing on Travis.

**Comment by DinisCruz** [comment]
@michaelhidalgo correct

**Comment by michaelhidalgo** [comment]
This one has been fixed. We can close it now.

**Comment by DinisCruz** [comment]
Correct here it is https://travis-ci.org/TeamMentor/TM_4_0_QA#L925
