### ISSUE TITLE
Login 'title' is lost when resizing login page

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#271]
Here is what it looks like when the window is resized to a smaller size 

![image](https://cloud.githubusercontent.com/assets/656739/5793907/327d6804-9f4f-11e4-98cc-a9c23e1055a7.png)

**Comment by luchia** [comment]
This has been fixed in my work on #254.

![screen shot 2015-01-21 at 12 48 54 pm](https://cloud.githubusercontent.com/assets/4547737/5830427/e49beb00-a16b-11e4-9e9e-5d8c3b562413.png)
![screen shot 2015-01-21 at 12 48 56 pm](https://cloud.githubusercontent.com/assets/4547737/5830426/e4987538-a16b-11e4-91b6-e82a73e22a2a.png)

**Comment by DinisCruz** [comment]
Yap, fixed

![image](https://cloud.githubusercontent.com/assets/656739/5833785/9a2fbb2c-a14e-11e4-84bd-1c1357cb1087.png)
