### ISSUE TITLE
Text scrols past the search bar in mobile view

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#296]
When scrolling text goes past the search bar in mobile view
![selection_067](https://cloud.githubusercontent.com/assets/1326120/5878914/bcbb0de4-a2f8-11e4-932a-7e19c8389186.png)

Probably related to this, in mobile view the top heading is not shown, only a small part of of it.
![selection_068](https://cloud.githubusercontent.com/assets/1326120/5878928/d75f6758-a2f8-11e4-9e6f-4ed18b738a8c.png)
 
I was hesitant in opening this, since I feel we already spend too much time on mobile Jade and I don't expect it to be used at all.  Hence its a P4

**Comment by luchia** [comment]
This was fixed in the referenced commit. Screenshots below and live version in the Dev branch:

![screen shot 2015-01-24 at 10 09 18 am](https://cloud.githubusercontent.com/assets/4547737/5885070/ea26a9b4-a3b1-11e4-93da-79ce477af8ec.png)
![screen shot 2015-01-24 at 10 09 50 am](https://cloud.githubusercontent.com/assets/4547737/5885067/ea2487f6-a3b1-11e4-885c-95679f2296aa.png)
![screen shot 2015-01-24 at 10 09 54 am](https://cloud.githubusercontent.com/assets/4547737/5885068/ea24f100-a3b1-11e4-8f16-763d1026c1f1.png)
![screen shot 2015-01-24 at 10 15 05 am](https://cloud.githubusercontent.com/assets/4547737/5885069/ea254b6e-a3b1-11e4-94c3-ea9f7613dd71.png)

**Comment by romichg** [comment]
Fixed
