### ISSUE TITLE
Search and Navigate page should only show top 'n' articles

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#298]
At the moment the search/navigate page shows all articles that exist on that query.

![image](https://cloud.githubusercontent.com/assets/656739/5889295/9c9189f2-a416-11e4-8777-f25a2b9bb663.png)

This doesn't really make sense since no user is going to flick more than (for example) 40 articles.

This also means that we send much more data to the user than we need to (for example on the page above we send to the user info about 794 articles (title, id, summary)

making a P0 since this part of the work being done on the search page (for example https://github.com/TeamMentor/TM_4_0_Design/issues/195)

**Comment by DinisCruz** [comment]
Here is the test that confirms the issue

```coffee
  it.only 'Issue 298 - Search and Navigate page should only show top n articles',(done)->
    jade.login_As_User ->
      jade.page_User_Graph 'Technology', (html, $)->
        $('#articles a').length.assert_Bigger_Than 100
        done()
```

**Comment by DinisCruz** [comment]
Done, now the top 20 are shown.

Test that checks it 
```coffee
  it.only 'Issue 298 - Search and Navigate page should only show top n articles',(done)->
    jade.login_As_User ->
      jade.page_User_Graph 'Technology', (html, $)->
        $('#articles a').length.assert_Is 20
        done()
```

Jade code that implements it:

```jade
mixin results-save-clear
	table
		tr
			td
				if results
					h5#resultsTitle= 'Showing ' + results.take(20).size() + ' of '  + results.size()
```

Here is what this looks like now:

![image](https://cloud.githubusercontent.com/assets/656739/5889401/bc00bf82-a41c-11e4-959a-76d4acb56c01.png)

**Comment by roman87** [comment]
Assigning to myself for QA

**Comment by roman87** [comment]
Why close :)?

**Comment by roman87** [comment]
This turns out to be quite a bad idea. I can narrow down the search to maybe 37 articles. And I can live with looking through title of 37 articles. In fact, I can live with looking through the titles of 100 articles. But as in the example below, you have just deprived me of looking through 17 articles. And I have no way of getting to them. 
What we should do, is what google does, and offer pages of content. so page 1 is 1-20 page 2 is 21-40 etc. 
For this beta lets remove this for now and load all the articles. Can we do that?
![selection_070](https://cloud.githubusercontent.com/assets/1326120/5890566/3376b5be-a42f-11e4-972d-8662e9f63951.png)

**Comment by roman87** [comment]
Bumping this as this is really a big issue and we need to fix it before we can show this to anyone! This is a lot more important!!!

**Comment by DinisCruz** [comment]
As discussed on skype, there is now a soft limit on 250, which is only visible is there are more than 250 articles

**Less than 250 articles** looks like this:

![image](https://cloud.githubusercontent.com/assets/656739/5907657/a33220e0-a598-11e4-846f-6e0242432719.png)

**More than 250 articles** looks like this:

![image](https://cloud.githubusercontent.com/assets/656739/5907656/99b63bc8-a598-11e4-8b90-a9106c165891.png)

**Comment by roman87** [comment]
this is done.
