### ISSUE TITLE
Change the top level prefix of the main navigate and search

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#303]
At the moment it is **/graph** and although that made sense in the first generation of this view, now we should come up with a better (and ideally shorter) name)

* http://localhost:1337/graph/Guidance
* http://localhost:1337/graph/Technology/
* http://localhost:1337/graph/Guidance,Logging

could maybe be

* http://localhost:1337/show/Guidance
* http://localhost:1337/show/Technology/
* http://localhost:1337/show/Guidance,Logging

or 

* http://localhost:1337/go/Guidance
* http://localhost:1337/go/Technology/
* http://localhost:1337/go/Guidance,Logging

or

* http://localhost:1337/v/Guidance
* http://localhost:1337/v/Technology/
* http://localhost:1337/v/Guidance,Logging

or

* http://localhost:1337/-/Guidance
* http://localhost:1337/-/Technology/
* http://localhost:1337/-/Guidance,Logging

**Comment by roman87** [comment]
I like show.

**Comment by DinisCruz** [comment]
Just implemented a fist pass of this and used '-' since that was the shortest, it actually looks quite nice:

![image](https://cloud.githubusercontent.com/assets/656739/5915901/f8578fe6-a602-11e4-917a-8d983a0a5bb7.png)

![image](https://cloud.githubusercontent.com/assets/656739/5915903/030e1702-a603-11e4-9536-7d841df7a234.png)

![image](https://cloud.githubusercontent.com/assets/656739/5915910/0f8acf5c-a603-11e4-9f47-66c2348210e0.png)

**Comment by roman87** [comment]
yes, it is short, but it makes no sense :). Can we do something more meaningful? like show, go, see, get, do, jump, fetch, dig, nav, follow. See what I mean? something that make sense?
Also, why did this change to a P0? This was something that we did not have to do at all now. Lets get into a discipline of working on what is agreed on to be a P0, and when done on what is agreed on to be a P1. If you feel something should be a P0/P1 and it is not, lets discuss.

**Comment by DinisCruz** [comment]
I did some refactoring that made this easy to implement, which is why when I did it I made it a P0

If you want I can keep it with the previous P mapping (in this case P2) and just move it to QA

In terms of only doing P0s, lets also not be to rigid here! 

If something happens to be easy to do, and can be implemented quickly (in less than 10m or 30m from start to end) then we should still do it. The point of the P0 is to indicate the priority, NOT to indicate the only things that can be worked on the code base!

If you don't agree with this approach, let's discuss

**Comment by DinisCruz** [comment]
For reference, the variable that currently controls this is the ```@urlPrefix``` as seen here
https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/controllers/Search-Controller.coffee#L30

Maybe one way to make it easier to find the right value is to:
a) allow that value to be configurable via a config file (i.e. easier to change)
b) support multiple values
c) if we do b), we most likely can also allow that value to be user-defined (which will make it easier to evaluate the multiple options)
d) ask our users to vote on it, which makes sense since they are the ones that will be using the links

**Comment by roman87** [comment]
With respect to P0, they indicate priority, which means that this is what our focus is. If we are working on something else then we are not working towards achieving our short main goals.

I agree that we should be flexible. If something happens to take 30m and is easy to implement and it helps us out, then certainly we can work on a P2 or even a P4. As long as it is ether a) invisible to the user b) something we all talked about.

However, this is an example of nether. In fact we already had spend too much time and energy discussing this to warrant it as a P2 to be worked on. Now if we start investing in surveys and voting we have now turned a P2 issue into a major discussion point that diverts our focus from all the P0 that we have. That is the issue that I have here. 
I will leave the issue open and move it back to P2 so that we can address this properly, in a proper forum when the time comes.  I will also assign it back to you so that we can change it to a few of the options at that time and request peoples opinion.

**Comment by DinisCruz** [comment]
this is done
