### ISSUE TITLE
Password reset button split in two lines when resizing the browser

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#313]
When resizing the browser, the  Password reset button text is split in two lines. Look at the following image taken from SauceLabs.

https://assets.saucelabs.com/jobs/911f78f6d78b42ef8f47d4c053983f77/0001screenshot.png

It was tested on Windows 7, and Firefox version 35.

**Comment by roman87** [comment]
Actually this is quite important one. Bumping it up to P1. Also it is part of Jade so its sprint2.

**Comment by luchia** [comment]
My referenced commits should have fixed this problem. I did some reading over the weekend and think taking the importance away from the button/link is acceptable because it is not a primary action for the user.

![screen shot 2015-02-03 at 12 29 48 pm](https://cloud.githubusercontent.com/assets/4547737/6013473/cd927eda-aba0-11e4-8ee3-5a4e5161eec7.png)
![screen shot 2015-02-03 at 12 29 52 pm](https://cloud.githubusercontent.com/assets/4547737/6013474/cd9532a6-aba0-11e4-8651-8cc11edbc27e.png)

**Comment by roman87** [comment]
Looks good. Closing this one
