### ISSUE TITLE
Number of articles is much less than in the library

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#321]
There are 2114 article in the Guidance library. TM40 only shows 794.
![selection_072](https://cloud.githubusercontent.com/assets/1326120/5923816/4285ec9a-a624-11e4-8100-9969ca915699.png)

**Comment by DinisCruz** [comment]
That is because TM Graph only imports articles that are currently mapped to a view, the other articles at the moment only exist on the file system (inside the library folder)

What 3.5 does is a special hack to do a sweep after the library load, and do a diff between what is on the file system and is loaded.

So the question for 4.0, is do we still support that kind of 'unlinked' article?

**Comment by roman87** [comment]
Thats a good point. I think we still need to load them as we need to search through them? The problem is, what happens after 100 of these are found in a search and there is no way to take some out because they don't belong to any keyword on the lefthand side. I suppose they still belong to keywords on the right?

**Comment by DinisCruz** [comment]
yes they would still have the keywords on the right (since that comes from the metadata)

**Comment by DinisCruz** [comment]
Btw, note that it is possible to import these extra articles, specially since they will still bring it all the metadata

what will be 'broken' is the navigation view, which will not have those articles

**Comment by roman87** [comment]
Yea so we need to fix it on the content side. It doesn't make sense to display 100 articles with no way of drilling down to them. I will let Serge know.

**Comment by roman87** [comment]
Closing this issue here as it is a content issue.
