### ISSUE TITLE
Who is the user?  And other observations and comments ...

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#346]
The entry screens seem very sales focused and seems to want the user to buy it.  There are all sorts of pretty benefit statements and feature descriptions, but there's no place to pay.  Instead it just asks the user to sign-up.   

My understanding of TM is that it is the eGuidance component of TEAM Academy and that article content was linked into eLearning modules and that it could be used in conjunction with various IDE's to enhance the developers experience with rich text describing how to fix vulnerabilities--and that the only reason someone would be seeing the interface was if their company had already bought the product.  So,  I don't understand what all the preamble is about and would have much rather have just been presented with a login or signup screen.

Some of the language used in the preamble is a little off as well, however, when I try to get back to the beginning to find it so I can comment, it takes me to a corrupted screen that wants me to select stuff:

![screen shot 2015-01-28 at 3 22 25 pm](https://cloud.githubusercontent.com/assets/2352439/5946140/80dc998e-a701-11e4-99c8-dab7f392cfea.png)

If I click on the TM Logo, expecting to be returned to the home screen I get what looks like the old TM UI:

![screen shot 2015-01-28 at 3 25 47 pm](https://cloud.githubusercontent.com/assets/2352439/5946205/f89bf9c4-a701-11e4-997a-5c73c34d1b81.png)

Going back to the landing screen and clicking Navigate results in a pleasant experience.  I like the look and feel of the list manager.  It feels very modern and intuitive.  I unfortunately seem to have broken it by trying to get back to the master list by first clicking on Guidance at the top of the main list, and that having no effect, clicked Navigate.  That refreshed the screen but didn't repopulate it.

![screen shot 2015-01-28 at 3 32 16 pm](https://cloud.githubusercontent.com/assets/2352439/5946339/e239b3c8-a702-11e4-8ef9-5f5f736108ca.png)

So,  when I did have the list to work from, as I said, it felt modern and intuitive and I liked it.  When I clicked on article to read however all that modern goodness seems to go away and the I was left with a slightly formatted, borderless document that was not anywhere near as cool as the list manager look and feel.

The list manager was nice and I like it a lot.  The only issue was when I had a long list of items to scroll through, the Guidance and Filter panes scrolled away with the list items.  It wold be cool If users could change filters or guidance parameters without having to scroll all the way back to the top of the list.

I realize that the current UI is a mixture of old and new.  I like the new, don't like the old, and think the entry point is trying to sell something that doesn't need to be sold.  A tutorial might be nice.

One other thing,  the EULA is out of data.  The new version is on the gDrive under Contracts.

**Comment by luchia** [comment]
We don't want the user to necessarily buy, but we're definitely trying very hard to get people to sign up - which is why we don't have any payment options upfront. We want people to get a feel for it first and we also want hands-on contact with everyone that comes through the application in terms of having follow up calls/emails/contact with the user throughout their trial period.

We're working on having a new user onboard system for Flare which is going to take our new user from sign up to TM-pro. The difficult thing about Jade is that we're limited by what we can do because we need to supply an application that works in legacy browsers, which doesn't leave us much room to move around. We're addressing this in Flare where things can move and look more seamless.

@DinisCruz is currently working on the article view and it aligns with the current style of the 4.0 design. You can also see the solution that I came up with on #350 in terms of the filters and collapsing them. It's really cool that I built that with CSS and only using the :hover pseudo-element, so it will work on legacy browsers.

We're also setting up a route that lets people log in immediately - something like teammentor.net/log-in for returning users.

For the rest of the comments, I don't know anything about them, so I'll leave them up to the other members of the team @roman87 @michaelhidalgo @DinisCruz.

**Comment by roman87** [comment]
Thank you so much @pjenney58 . Looks like you hit on a whole bunch of bugs all at once :). The corrupted screen is most likely due to some of the Seattle guys testing the non-working search function. The blank page is due to the backend bug.  The old UI is actually only there for a single function that should go away in next beta. 
Now what is interesting is that when you click TM logo it should never bring you to the old version. We should have another beta out by the end of the week. I would really appreciate if you can take a look again after that is out. 
Regarding your question on who is the user. You are absolutely right. We are selling to corporate customers. And obviously a customer deployed site will not have all the marketing stuff. Currently we have an ability to sign up for a 30 day trial. This is what we are heavily pushing with this version. The idea is that the more people sign up and try TM, the more people will end up buying it. 
Regarding the EULA. We will update it. I also had a question regarding our privacy policy. Since we are collecting email addresses, do we need to have one? Or is it part of our EULA?

Thanks.

**Comment by roman87** [comment]
TTL Expired. Closing
