### ISSUE TITLE
Validate the search string to sanitize from potential injeciton attacks. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#355]
Given that the search string passes directly to the graphDB for query we need to be sure that we sanitize it properly to prevent potential injection attacks. An interesting case would be if someone actually wants to search for ```<script>``` tag in our content.

**Comment by DinisCruz** [comment]
Actually as mentioned already on the main issue text, this is one of those cases where we can't do anything to the search text since it might have an impact of the graphDB ability to provide a good answer. 

We want users to search for XSS and SQLi injection payloads, since those search testms should take them to the relevant articles (on both exploiting and fixing those issues)

I think there is a case to limit the maximum size of the query, but even them, should that be done by TM_Design or by TM_Graph? (See https://github.com/TeamMentor/TM_4_0_Design/issues/370 for the idea of doing a global filter)

From a security point of view, I think we should be doing this type of 'secure handing of user data' as close as possible to the entity handling the data. In this example, the Graph_DB will also need to have this checks, so it makes sense for this to be done there (specially since we will eventually also expose the swagger APIs to TM users)

**Comment by roman87** [comment]
Well one thing we can do is to encode the user input, and make sure we have our articles encoded as well. This way if we use the same encoding the search will not be affected, but the ability to execute anything will. 
Length is certainly a parameter. Though as I mentioned in the #370 I am not sure that having a global length is a way to go.

**Comment by DinisCruz** [comment]
we can't encode the input since that will affect the quality of the search. 

For example I remember somebody complaining on 3.5 that they were not able to search for encoded strings (which is yet another type of search query we need to support, since we have articles with multiple encoding examples in them).

recaping:

* on 4.0 Design we can't touch the search string (apart form maybe max length)
* it is the GraphDB responsibility to handle the input provided (and use it on the search)
* the graphDB is all done on top of graph objects, so apart from length probs, there should be no injection capabilities
* the 4.0 Design views are all made using Jade, so there is no need to encode on the controller since the Jade parser will already do that (in fact if you encode it on the controller, you will have double encoding problems)

**Comment by roman87** [comment]
Ok agreed. As far as the last bullet. Are the views also made using Jade?

**Comment by DinisCruz** [comment]
yes ALL views are made of Jade, which is why I don't worry about @luchia creating an XSS vuln, since there are very few ways to have unescaped content (which are easy to spot, but eventually should also be covered by a test)

**Comment by DinisCruz** [comment]
since the size will be handled by Node and so will the handling of bad urls, we should be good with this issue

**Comment by roman87** [comment]
Agreed. closing
