### ISSUE TITLE
Recent articles are empty for new user.

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#384]
We should show nothing at all in case recent articles are empty. Otherwise it looks confusing.

**Comment by DinisCruz** [comment]
Note that on the current version (pushed to master), you don't get the recent articles at all (which is a bug and will be fixed soon (due to the use of a new Article-Controller, the data is now on a different location)

Once it is wired back, you will not see anything until you view the first article

**Comment by DinisCruz** [comment]
Also fixed with latest push

An easy way to test this is to login the site using a new session (like Chrome's incognito mode)

![image](https://cloud.githubusercontent.com/assets/656739/6461852/17b6fa8e-c19c-11e4-978a-ad0d770c48a2.png)

after opening up an article it will be shown

![image](https://cloud.githubusercontent.com/assets/656739/6461859/231c3484-c19c-11e4-93b0-4d04742acc8c.png)

**Comment by roman87** [comment]
This is fixed
