### ISSUE TITLE
Headings size are are too large, seems like paragraph headings are bigger than the title

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#394]
![selection_082](https://cloud.githubusercontent.com/assets/1326120/6070301/6096effe-ad59-11e4-9abc-bd52d3a8857c.png)

**Comment by luchia** [comment]
This has definitely been fixed on Dev. I'm not sure why it's not showing on your version.

![screen shot 2015-02-06 at 8 43 16 am](https://cloud.githubusercontent.com/assets/4547737/6071205/03ffe9b8-addf-11e4-8ad7-b40b45fcdc28.png)

**Comment by DinisCruz** [comment]
Here is what it looks to me

![image](https://cloud.githubusercontent.com/assets/656739/6071874/d5432348-ad92-11e4-9e78-67ada8c24a43.png)

![image](https://cloud.githubusercontent.com/assets/656739/6071880/df83a134-ad92-11e4-919a-bc39c1c73d7c.png)

**Comment by luchia** [comment]
So this is what I have at the moment after working on #396 all day. Can you please let me know if you still can't see it as I have definitely merged this work onto Dev?

![screen shot 2015-02-06 at 4 37 20 pm](https://cloud.githubusercontent.com/assets/4547737/6075453/9139654a-ae1e-11e4-9b18-a4fb12c65af3.png)
![screen shot 2015-02-06 at 4 37 22 pm](https://cloud.githubusercontent.com/assets/4547737/6075454/913aa608-ae1e-11e4-8fac-893999f3f8e9.png)

**Comment by DinisCruz** [comment]
I think the issue might be caused because the **Lib_Vulnerabilities** library (used by default by TM_Design) might be using different style attributes as the **Lib_UNO** Library (the https://github.com/TeamMentor/TM_4_0_Design/issues/317 fix help to test this).

This also raises the question that we need to double check all articles for style consistency (for example all articles should be using a particular type of heading for the titles)

**Comment by roman87** [comment]
They are still broken. I think @DinisCruz  is right about the different styles in each Library. See if you can use these instructions to clone the Lib_Uno library. https://github.com/TeamMentor/TM_4_0_Design/wiki/How-to-build-and-run-the-GraphDB
I just checked and you have read rights on that repo.

![selection_084](https://cloud.githubusercontent.com/assets/1326120/6098116/da573f56-afa2-11e4-9c8b-e1c7dec92b96.png)

**Comment by roman87** [comment]
Otherwise catch me on skype in your morning and I will walk you through the setup.

**Comment by luchia** [comment]
So I cloned the Lib_Uno library and got it up and running fine. However, the article still appears as it should from my end, including after clearing my cache.

![screen shot 2015-02-10 at 10 02 52 am](https://cloud.githubusercontent.com/assets/4547737/6118778/02821238-b10d-11e4-92a4-4944ba24ac53.png)

**Comment by roman87** [comment]
This seems like a very weird bug. When I go to the above URL, graphDB crashes

**Comment by roman87** [comment]
I will take this to see if I can reproduce it.

**Comment by roman87** [comment]
@luchia can you try to duplicate this with the latest GraphDB? Here is one of the articles that looks bad:

http://localhost:1337/article/article-b15092e871fa


![selection_104](https://cloud.githubusercontent.com/assets/1326120/6192472/63da8e3c-b380-11e4-9a16-a9edcf2fac33.png)

**Comment by luchia** [comment]
As Dinis suggested on a morning meeting last week, I've added an article title and article content class that affects the layout. This is a short term fix relating to our article content formatting.

![screen shot 2015-02-17 at 10 01 39 am](https://cloud.githubusercontent.com/assets/4547737/6220929/14d2e866-b68c-11e4-9534-dd238ced8978.png)

**Comment by roman87** [comment]
I don't see any change :)
![selection_108](https://cloud.githubusercontent.com/assets/1326120/6223216/c0b3f7ac-b631-11e4-8008-d905b8a56107.png)

**Comment by luchia** [comment]
Alright, I've finally been able to see what everyone else has been seeing. I wasn't getting what you can see before so I guess my library swapped over to the other one we were talking about? Anyway, no more trying to hack a fix for something I can't see.

This has been fixed in the referenced commit and can be seen below.

![screen shot 2015-02-18 at 10 16 49 am](https://cloud.githubusercontent.com/assets/4547737/6239814/9c650ee6-b757-11e4-983a-85f4a81c9ccb.png)
![screen shot 2015-02-18 at 10 16 54 am](https://cloud.githubusercontent.com/assets/4547737/6239815/9c676808-b757-11e4-8bf9-9c6633ec733a.png)
![screen shot 2015-02-18 at 10 16 58 am](https://cloud.githubusercontent.com/assets/4547737/6239817/9cab4adc-b757-11e4-950f-f07ba0523f9c.png)
![screen shot 2015-02-18 at 10 17 02 am](https://cloud.githubusercontent.com/assets/4547737/6239816/9ca57dfa-b757-11e4-9e86-48ea211fdc10.png)

**Comment by DinisCruz** [comment]
It's better, but the font sizes of the titles still look to big  (to me)

![image](https://cloud.githubusercontent.com/assets/656739/6241035/ed0355ea-b70e-11e4-9517-343ddf841fff.png)

**Comment by michaelhidalgo** [comment]
Yes I agree, it also looks to big to me.

El martes, 17 de febrero de 2015, Dinis Cruz <notifications@github.com>
escribió:

> It's better, but the font sizes of the titles still look to big (to me)
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/656739/6241035/ed0355ea-b70e-11e4-9517-343ddf841fff.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/394#issuecomment-74794895>
> .
>


-- 
Sent from Gmail Mobile

**Comment by roman87** [comment]
Actually it looks fine to me :). But if you make it a bit smaller it probably would not hurt. Glad you can see now what we see :).

**Comment by luchia** [comment]
@DinisCruz @michaelhidalgo - what do you think of the changes made in the referenced commit?

**Comment by roman87** [comment]
This looks fine to me. Closing in 2 days if nobody complains.

**Comment by roman87** [comment]
Nobody complained. Closing.
