### ISSUE TITLE
Weird search results when searching for "Prevent Unsigned"

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#401]
![selection_088](https://cloud.githubusercontent.com/assets/1326120/6098467/b9aaa7b0-afad-11e4-9d8e-e7570e448d4a.png)

**Comment by DinisCruz** [comment]
humm, i get 

![image](https://cloud.githubusercontent.com/assets/656739/6114514/9673c846-b096-11e4-81f5-7418db0265a7.png)

**Comment by DinisCruz** [comment]
referenced commit fixes this bug

The root cause was the fact that the graph query generated from the provided text would return:
 -  a string when there was 1 search match and 
 - an array when there was more than one result 

The reason why there was always 20 'empty' search results, is because the id of an article is by default made of 20 chars: article-a670c1fcd3e3 (and a string is an array of chars)

**Comment by roman87** [comment]
Nice one! Good find! This is fixed.
