### ISSUE TITLE
Copyright should not be in the footer of all pages

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#403]
Copyright only should be shown when the users scrolls all the way down on the full article view page. Otherwise it takes too much space and diverts attention. From search and navigate.

**Comment by luchia** [comment]
This has been fixed in the referenced commit and the div is no longer sticky.

![screen shot 2015-02-10 at 7 27 11 am](https://cloud.githubusercontent.com/assets/4547737/6116250/fed72b34-b0f6-11e4-9047-d270f26a69db.png)
![screen shot 2015-02-10 at 7 27 06 am](https://cloud.githubusercontent.com/assets/4547737/6116241/e9d6a228-b0f6-11e4-97fc-f58928732dd4.png)

**Comment by roman87** [comment]
This is fixed.
