### ISSUE TITLE
Space between left and right main boxes is too large on singup and login page. Resulting text too narrow 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#408]
![selection_092](https://cloud.githubusercontent.com/assets/1326120/6101107/2a8383b0-afec-11e4-8ae7-304df10febbe.png)

Honestly, I like the older signup and login page much better. 
![selection_093](https://cloud.githubusercontent.com/assets/1326120/6101121/5738a71e-afec-11e4-92f6-40b4c5dad72f.png)

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

![screen shot 2015-02-10 at 7 43 09 am](https://cloud.githubusercontent.com/assets/4547737/6116484/b2fd90d4-b0f8-11e4-94df-e2e9cfe3e0be.png)
![screen shot 2015-02-10 at 7 43 12 am](https://cloud.githubusercontent.com/assets/4547737/6116485/b32b4e2a-b0f8-11e4-8c97-0700a9c429a3.png)

**Comment by roman87** [comment]
Looks much better now.
