### ISSUE TITLE
Filter numbers still look a bit weird on longer text

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#428]
It feels a bit weird when the number is out of line with other numbers. Give it some more thought. Perhaps wrap the text and keep the number justified? Or maybe make the table a bit wider? 

![selection_100](https://cloud.githubusercontent.com/assets/1326120/6190993/1f52085a-b374-11e4-90ef-2fa27cb5e15c.png)

**Comment by luchia** [comment]
Hey, I added a style that breaks the word within the table cell so that it sits nicer. Let me know what you think.

![screen shot 2015-02-17 at 9 48 55 am](https://cloud.githubusercontent.com/assets/4547737/6220780/6fb7580e-b68a-11e4-9cdc-969e5e40b610.png)
![screen shot 2015-02-17 at 9 49 05 am](https://cloud.githubusercontent.com/assets/4547737/6220781/6fb8e552-b68a-11e4-8223-996be186725b.png)
![screen shot 2015-02-17 at 9 49 14 am](https://cloud.githubusercontent.com/assets/4547737/6220782/6fc11a56-b68a-11e4-9af5-b710b57d3657.png)

**Comment by roman87** [comment]
So this still feels a bit weird, when the browser is of a certain size. But I guess we can live with this, if there is nothing much we can do. Don't break your head over this. 
![selection_111](https://cloud.githubusercontent.com/assets/1326120/6236748/302584fa-b6bb-11e4-9c63-096c7eace02a.png)

**Comment by roman87** [comment]
This is now more of a question. If we can fix it easily, lets do it, if not lets leave stuff like this for flare.

**Comment by luchia** [comment]
I can't really get it to break any better tbh.

**Comment by DinisCruz** [comment]
yeah, I think we can live with it (for now)

**Comment by roman87** [comment]
Ok lets go with the option where the link spans the entire line. Like it is now. Closing this.
