### ISSUE TITLE
Multiple encoding issues in http://localhost:1337/article/article-b90128ab8e3c

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#441]
![selection_106](https://cloud.githubusercontent.com/assets/1326120/6223185/f42d8536-b630-11e4-8488-8e4ca5020666.png)

https://beta35.teammentor.net/article/500ae131-3373-4246-b6f5-b90128ab8e3c
Is fine. We need to be able to display the same encoding as we do on 3.5 
![selection_107](https://cloud.githubusercontent.com/assets/1326120/6223186/f81b67c6-b630-11e4-8381-72f7e9f558bf.png)

**Comment by DinisCruz** [comment]
@michaelhidalgo can you write a test that finds the root cause of this issue

**Comment by michaelhidalgo** [comment]
The problem seems to be that the article was saved with the encoding issue (look for example https://raw.githubusercontent.com/TMContent/Lib_UNO/master/Checklist%20Item/500ae131-3373-4246-b6f5-b90128ab8e3c.xml?token=ABptw9Y8Cl3lGGWX7iKry2RS4lrN5Swhks5U8mw-wA%3D%3D).

Note that the text contains this problem: 

 <Title>User&amp;#39;s Login Credentials Are Validated Before Use</Title>

A possible solution could be to fix the article at the time it is being imported to JSON  with xml2js.  It seems that we could use ent (Encode and decode HTML entities) https://www.npmjs.com/package/ent.

I will do a POC to see how it works.

**Comment by michaelhidalgo** [comment]
Ok so I was playing around with this issue. This is how this article looks in beta (https://beta.teammentor.net/article/article-b90128ab8e3c)

![screen shot 2015-02-23 at 11 08 46 am](https://cloud.githubusercontent.com/assets/1732035/6332641/67838c90-bb4c-11e4-995c-fe5d3c61be7a.png)

And after using ent (https://www.npmjs.com/package/ent#readme) to decode the content, this is how it looks like : 

![screen shot 2015-02-23 at 11 10 41 am](https://cloud.githubusercontent.com/assets/1732035/6332652/8e5162ac-bb4c-11e4-95a4-3fcdad1ce12a.png)

However, decoding the article's content prior to import them to JSON is not a solution because it might exposes risk like this one : 

![screen shot 2015-02-23 at 11 07 03 am](https://cloud.githubusercontent.com/assets/1732035/6332668/b47340d6-bb4c-11e4-969b-72207adde9d8.png)

because the code example contains this <script>alert('XSS!');</script>

**Comment by michaelhidalgo** [comment]
https://github.com/TeamMentor/TM_4_0_Design/issues/473

**Comment by roman87** [comment]
As discussed on the call, articles that contain ```<script>``` we should detect and throw as an exception to edit manually. Other than that I think this works pretty well. Lets see if we can decode the content and then write it back as the original XML so that we can fix it in the Lib_UNO library instead of fixing it on import.

**Comment by michaelhidalgo** [comment]
I found the source of the problem for these encoding issues. So far I think all them as been fixed, although I'm writing a test for that.

The problem happens when there are a double encoding issue in the article : 
In this case, note how the  & is encoded as ```"&amp;"``` in the article's source code.

<Title>User&amp;#39;s Login Credentials Are Validated Before Use</Title>

The problem is that when this article is rendered in Jade, it becomes : 
```<Title>User&#39;s Login Credentials Are Validated Before Use</Title>```

As you can see here. It means that when the article is rendered, the first layer of decoding, decodes the ampersand ( from ```"&amp;"``` to &). Which means that the text is still encoded.

![screen shot 2015-03-03 at 10 42 57 am](https://cloud.githubusercontent.com/assets/1732035/6467152/fbf80720-c191-11e4-95dc-cbc32a40520d.png)

So the solution in this case is to look in the raw XML and replace the ```"&amp;"``` to &. That way we remove the first layer of encoding in the &. When the HTML is rendered it will be displayed fine.

Note how the code snippets are displayed fixed : 

![screen shot 2015-03-03 at 10 47 40 am](https://cloud.githubusercontent.com/assets/1732035/6467260/a7d77b0c-c192-11e4-9bde-77d551a73980.png)

**Comment by roman87** [comment]
Ok so is the solution basically to run through the decoder? What happens to doubly encoded code examples inclosed in  ```<pre>``

**Comment by michaelhidalgo** [comment]
As far as I've been able to test, those scenarios are already covered : 

If you look at this article https://beta.teammentor.net/article/article-4199598f3446

![screen shot 2015-03-03 at 11 56 21 am](https://cloud.githubusercontent.com/assets/1732035/6468660/304a13c4-c19c-11e4-98c3-9f636eff6490.png)

After the fix, running it locally, it becomes 

![screen shot 2015-03-03 at 11 57 17 am](https://cloud.githubusercontent.com/assets/1732035/6468684/580575f2-c19c-11e4-86ea-a325b049e3ed.png)

**Comment by michaelhidalgo** [comment]
Related to https://github.com/TeamMentor/TM_4_0_Design/issues/395

**Comment by michaelhidalgo** [comment]
The solution to this problem consist on modifying the raw XML article and replace the double encoding for the  "& ". Therefore ```"&amp;"``` becomes ```"&"```.

However, few articles needs to keep ```"&amp;"``` to delineate how Html Encoding should be used for special characters. 

This articles needs to be fixed manually and converted to Markdown.

```JavaScript
How To\a4a8c95b-24d6-4e3a-a49b-cc55482c71e2.xml                                                                                                     
Articles\3b46e08b-1e8a-4dbf-b7bc-39a13c8afcbc.xml                                                                                                                                                                                                                                                                                                     
Articles\f40bd3e2-2f0c-4354-b46a-ea9b4f3831c7.xml                                                                                                        
Guideline\f83b953a-9b0c-406a-b274-9b2962d9c4e7.xml                                                                                                  
How To\60134abf-ea74-4166-8d8f-d5c790638b56.xml 
b27e32f9-7827-41e9-9290-6069bd01e2d4
```

Actually, this article in production https://teammentor.net/article/b27e32f9-7827-41e9-9290-6069bd01e2d4, renders the search box : 

![screen shot 2015-03-10 at 1 52 09 pm](https://cloud.githubusercontent.com/assets/1732035/6583832/76f5178e-c72c-11e4-923e-89f26ccde044.png)

I used a PowerShell script to listed all the files with keywords like Html Encoding, ampersand, and

**Comment by roman87** [comment]
So we only have 6 articles to fix manually?

**Comment by michaelhidalgo** [comment]
Yes, those six articles has this pattern : 

![screen shot 2015-03-10 at 3 45 36 pm](https://cloud.githubusercontent.com/assets/1732035/6586096/6b613884-c73c-11e4-82d7-c053d50fd675.png)

**Comment by michaelhidalgo** [comment]
I've created individual issues for the articles that needs to be fixed.

https://github.com/TMContent/Lib_UNO/issues

**Comment by roman87** [comment]
Great, thank you, good stuff on this one!
