### ISSUE TITLE
Headphones in the main picture date the picture

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#450]
Ok I am knit-picking here, but So just looking at the main TM landing page and the main picture, you see what looks like apple headphones. These headphones are no longer made by apple. Which means the picture is at least 3-4 years old. Does this somehow date our content :)?

**Comment by DinisCruz** [comment]
On the topic of that picture, what is its license? 
@luchia where did you get it from?

In terms of the content, it would be cool to look at other options, in fact we could even make it a bit random?

Btw, the image is still 666kb (http://beta.teammentor.net/static/assets/stock-img/bg-img.jpg) can't we reduce it? (does it need to be 2000 pixels wide?)

**Comment by DinisCruz** [comment]
This is what happens on low res

![image](https://cloud.githubusercontent.com/assets/656739/6238331/17774f6a-b6f2-11e4-8b20-54d54e539aa4.png)

**Comment by luchia** [comment]
It could date our content. I'll look for something else. Dinis, this photo comes from [unsplash](unsplash.com) which is an open-source photo library.
I'll try to find something that  tiles nicely for Jade. This won't be an issue with Flare as we'll be using SVG's to look after retina display users.

**Comment by luchia** [comment]
Thoughts on the following images? I liked these because they are easy enough to blend them so they repeat nicely. I would want to remove logos -

![95cdfeef](https://cloud.githubusercontent.com/assets/4547737/6239971/4b0c96a2-b759-11e4-91b3-22baea9f90f5.jpeg)
![39982a21](https://cloud.githubusercontent.com/assets/4547737/6239970/4b0c36e4-b759-11e4-8460-8caf002096ea.jpeg)
![bw-room](https://cloud.githubusercontent.com/assets/4547737/6239972/4b0f9726-b759-11e4-8e01-98c5071a71d2.jpeg)

**Comment by DinisCruz** [comment]
what do these images look like when titled?

Re use of images from unsplash  we should put that reference/credit somewhere

**Comment by roman87** [comment]
I like the last one, not sure why. Maybe because it lacks the apple theme. We need to cater to people running all OSes. Most enterprises tend to run windows. I agree with @DinisCruz it would be cool to have them random, but maybe next release. Regarding credit and license. We should check if we need to give credit, and not to bother if we don't. We should also check if the license allows us to modify the image.

**Comment by luchia** [comment]
> All photos published on Unsplash are licensed under Creative Commons Zero which means you can copy, modify, distribute and use the photos for free, including commercial purposes, without asking permission from or providing attribution to the photographer or Unsplash.

**Comment by luchia** [comment]
This is what they look like tiled -

![test1](https://cloud.githubusercontent.com/assets/4547737/6261514/94555f96-b840-11e4-9d9a-506d2a477040.jpg)
![test2](https://cloud.githubusercontent.com/assets/4547737/6261513/9454bb68-b840-11e4-9b08-c62cb0914be3.jpg)
![test3](https://cloud.githubusercontent.com/assets/4547737/6261515/945a34b2-b840-11e4-9313-feed56b98029.jpg)

**Comment by roman87** [comment]
Ok, any other ideas :)? I am not sure I am a fan of the mirror image here :)

**Comment by DinisCruz** [comment]
what happens with the first image on the next tile? It looks like the user will have 3 hands :)

**Comment by roman87** [comment]
Hahah.. well.. it may actually serve as  advertizement - TEAM Mentor - we are your third hand in fixing bugs :)

**Comment by roman87** [comment]
How about this one :)  This is a staircase from Harry Potter (so I was told as I can't watched the movie. You'd need to edit the people out though :).


![dsc01222](https://cloud.githubusercontent.com/assets/1326120/6317017/a618f72a-ba0b-11e4-9677-1439d7b224e9.JPG)

**Comment by luchia** [comment]
That's a lot of work to get rid of all those people... It's also not the best quality (there's motion blur in the photo) and I don't think it would fit the overall image we are going for.

This is what they look like tiled without reflection. I added the reflection because I thought the repeated image looked strange without it. 

![test1](https://cloud.githubusercontent.com/assets/4547737/6321618/fadbc49e-bb51-11e4-86b2-b6988a8a3d7a.jpg)
![test2](https://cloud.githubusercontent.com/assets/4547737/6321619/fadbf630-bb51-11e4-8a47-7e851376837d.jpg)

What about more text-based images?

![fvd9myegrued3zlne2gs__dsc0033-1](https://cloud.githubusercontent.com/assets/4547737/6321646/910890a0-bb52-11e4-96cc-96e8eae716a7.jpg)
![photo-1423001369568-657dfdb9ce03](https://cloud.githubusercontent.com/assets/4547737/6321645/9107a1cc-bb52-11e4-8094-b007656841a3.jpeg)
![tkloe7nnq7mnmsiuijby_hm](https://cloud.githubusercontent.com/assets/4547737/6321647/910ccd8c-bb52-11e4-8d14-29020b575ba1.jpg)

**Comment by roman87** [comment]
I wasn't really serious with my image  :)  I just thought the idea of some wizzard library would be cool. Anyways, I like the last one and the second to last one.

**Comment by luchia** [comment]
I changed the image over to the one that I think works best. Let me know what you think :)

![screen shot 2015-02-24 at 5 05 48 pm](https://cloud.githubusercontent.com/assets/4547737/6344637/1f26523e-bc4b-11e4-8ffd-c1a6cef9e610.png)
![screen shot 2015-02-24 at 5 05 54 pm](https://cloud.githubusercontent.com/assets/4547737/6344638/1f26dc5e-bc4b-11e4-9c1a-e5cafc62f614.png)
![screen shot 2015-02-24 at 5 09 20 pm](https://cloud.githubusercontent.com/assets/4547737/6344639/1f51bb54-bc4b-11e4-8fd5-504577a6b294.png)

**Comment by roman87** [comment]
This can probably be considered fixed. However we still have an issue here:  https://github.com/TeamMentor/TM_4_0_Design/issues/356

**Comment by roman87** [comment]
How does everyone else like the image?

**Comment by luchia** [comment]
See comments on #356.

**Comment by luchia** [comment]
@DinisCruz @michaelhidalgo @tekgirl77 what do you think of the new image?

**Comment by luchia** [comment]
Resounding yes then :P

**Comment by roman87** [comment]
I can hear the applause :) I guess this image is not the most amazing, but for now will do :) Closing.

**Comment by DinisCruz** [comment]
I'm good with the image :)
