### ISSUE TITLE
Hard to see Forgot password link 

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#460]
I'm not sure if we had an issue for this or if we agreed on it but to me it's hard to see the forgot password link, maybe if it was a little bit darker it would be better, also the font size seems to be small compared to other elements in the screen.

![screen shot 2015-02-18 at 1 19 35 pm](https://cloud.githubusercontent.com/assets/1732035/6255413/5ffdbe26-b775-11e4-8640-c05d7dfc5eec.png)

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

Normal state
![screen shot 2015-02-19 at 2 10 58 pm](https://cloud.githubusercontent.com/assets/4547737/6261536/31714b78-b841-11e4-9e91-113d123aa2ff.png)

Hover state
![screen shot 2015-02-19 at 2 11 02 pm](https://cloud.githubusercontent.com/assets/4547737/6261537/31740a70-b841-11e4-8b39-6a6e07834946.png)

**Comment by michaelhidalgo** [comment]
@roman87 what do you think? I'm not sure if the reset link should be inside a frame (i.e like a button).

**Comment by luchia** [comment]
My reasoning for changing it to a link is because it is a secondary piece of information and isn't vital to the user to get in to the application. I also thought that it was kind of confusing because buttons should post data and it doesn't do that - it links to a new page.

As per our meeting this morning, Michael noted the colour is very green and it doesn't really tie in with the rest of the application links. I made some changes today that I think suit the style better -

![screen shot 2015-03-06 at 7 49 21 pm](https://cloud.githubusercontent.com/assets/4547737/6523275/fec55a34-c439-11e4-91d2-65d7f8853a22.png)

:hover state

![screen shot 2015-03-06 at 7 49 24 pm](https://cloud.githubusercontent.com/assets/4547737/6523276/fec6656e-c439-11e4-8cca-8785b148e64f.png)

**Comment by roman87** [comment]
This looks good, should have been on its own branch though :)
Lets merge it into Dev.

**Comment by luchia** [comment]
It was done over the weekend.

**Comment by roman87** [comment]
Yep, looks good in dev
