### ISSUE TITLE
Narrow version on HIDPI screens switches to smaller size than just a few pixels less on a regular size browser

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#530]
![selection_150](https://cloud.githubusercontent.com/assets/1326120/6604776/43948f5c-c801-11e4-8ac1-fc0afabda666.png)

![selection_151](https://cloud.githubusercontent.com/assets/1326120/6604783/54912cd4-c801-11e4-86b0-a2f571b86167.png)

**Comment by luchia** [comment]
I fixed this by setting a max-width, but the only issue is that because the navigation is fixed, it will not sit correctly -
![screen shot 2015-03-12 at 1 02 08 pm](https://cloud.githubusercontent.com/assets/4547737/6611468/262dac3e-c8b8-11e4-8eaa-cc1463cbe8dd.png)

We can fix this by using CSS calc() to do the maths **but** it's not supported by legacy browsers -

![screen shot 2015-03-12 at 1 07 02 pm](https://cloud.githubusercontent.com/assets/4547737/6611505/b11a75a2-c8b8-11e4-8d54-e5a696117507.png)

Which leaves us with making the navigation **not** fixed to solve this problem - 
![screen shot 2015-03-12 at 1 02 48 pm](https://cloud.githubusercontent.com/assets/4547737/6611467/262b7540-c8b8-11e4-9c85-3f55f404873a.png)
![screen shot 2015-03-12 at 1 02 51 pm](https://cloud.githubusercontent.com/assets/4547737/6611469/262f0cb4-c8b8-11e4-8abf-d7f1d44b8305.png)

**Comment by roman87** [comment]
Ok in that case lets leave it as it was and move this issue to Flare. Agree?

**Comment by roman87** [comment]
As it was, I meant with the issue described here but with the fixed navigation. Basically revert the change :)

**Comment by luchia** [comment]
This has been fixed on the Lucy branch.

**Comment by roman87** [comment]
Ok looks good. I am moving this issue to Flare

**Comment by romichg** [comment]
Done
