### ISSUE TITLE
Switch default editor for 3.6 to markdown

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#539]

**Comment by michaelhidalgo** [comment]
Ok,just to confirm :  Markdown editor should be the default for  <b>markdown</b> and <b> html</b>, am I right?.

I did the change in the backend,so if you edit an html article like this : 

![screen shot 2015-03-14 at 10 53 38 am](https://cloud.githubusercontent.com/assets/1732035/6652546/25d28ce2-ca38-11e4-9e83-3a07628841fe.png)

Should we change the editor button for HTML to say "Edit MarkDown" rather than "Edit WYSIWYG"?

![screen shot 2015-03-14 at 10 59 30 am](https://cloud.githubusercontent.com/assets/1732035/6652592/6d972276-ca39-11e4-9a4d-49be8eeb90a0.png)

**Comment by roman87** [comment]
Perfect. Yes lets change it to say "Edit in Markdown Editor"

**Comment by michaelhidalgo** [comment]
Cool, thanks :)

**Comment by michaelhidalgo** [comment]
This has been fixed in this  PR https://github.com/TeamMentor/Dev/pull/172

**Comment by roman87** [comment]
Nicely done.
