### ISSUE TITLE
Should we - Map our current workflow to SCRUM

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#552]
I was reading about Scrum this weekend and I think our current dev workflow is already very Scrum-like but there are a number of areas we can improve it.

Map these areas and suggest ideas

**Comment by roman87** [comment]
The beauty of SCRUM is that it can be modified the way it fits. And I've modified it to where I think I think our work flow works pretty well for now. and is pretty efficient. I was playing with many tools, including JIRA and ended up concluding that they add more overhead than we need at the moment. For the size of our team stories defined in TeamMentor/Master and task defined in other repos, work well. I also cannot fix the Sprints in terms of time simply due to our limited resources. 
But I am open to ideas.  :)

**Comment by roman87** [comment]
Also, this is not a quality issue. :)

**Comment by DinisCruz** [comment]
yap, and as the team grows and matures (specially thinking of other SI employees that would like to contribute/help or power users from customers), it will help to document and map out (in a wiki page for example) our current Scrum practices (since we are actually doing it quite nicely :)  )

**Comment by roman87** [comment]
I think it is mainly all documented on tm4tm already. Probably needs a bit of a polish.  I opened a specific issue for it: https://github.com/TeamMentor/TM_4_0_Design/issues/559

**Comment by DinisCruz** [comment]
ok , I added a note to it
