### ISSUE TITLE
Create a doc page for possible search options

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#573]
This is requested by @bendixspring here: https://github.com/TeamMentor/TM_4_0_Design/issues/566

**Comment by roman87** [comment]
@bendixspring the documentation now explains examples (quick start guide) and general instructions (searching and filtering) on how to perform searches. Could you take a look and let us know if this works.

**Comment by BendixSpring** [comment]
I think this documentation is a big improvement!

I would suggest that a bit more be added to the searching page: https://beta.teammentor.net/help/00000000-0000-0000-0000-00000018204d
that describes the search in more detail, because it does **not** have the functionality people expect (i.e., google-like searching).

Can't search for exact phrases; does implicit "AND", etc.

**Comment by romichg** [comment]
done in latest doc
