### ISSUE TITLE
broken help images on beta.teammentor.net

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#593]
First reported on https://github.com/TeamMentor/TM_4_0_Design/issues/589 the help images are not working on the beta.teammentor.net site

![image](https://cloud.githubusercontent.com/assets/656739/6694224/a592c646-ccd0-11e4-9815-c2cafd1265b3.png)

this is a weird because they are working locally

![image](https://cloud.githubusercontent.com/assets/656739/6694235/bb4ac222-ccd0-11e4-94d0-8801b5c869ab.png)

This could be a problem with the url forwarding on the IIS server

**Comment by DinisCruz** [comment]
Here is what should happen 

http://localhost:1337/Image/abc redirects to https://raw.githubusercontent.com/TMContent/Lib_Docs/master/_Images/abc

![image](https://cloud.githubusercontent.com/assets/656739/6694290/42b9d66c-ccd1-11e4-80e5-1e34ce1f9f44.png)

here is what is happening on beta.teammentor.net

![image](https://cloud.githubusercontent.com/assets/656739/6694301/52638fc2-ccd1-11e4-8fbe-122c2cd1e511.png)


Here is the relevant parts of the source code (in **Help-Controller.coffee**):

```coffee

@.gitHubImagePath  = 'https://raw.githubusercontent.com/TMContent/Lib_Docs/master/_Images/'

....

  redirect_Images_to_GitHub: ()=>
    @.res.redirect @.gitHubImagePath + @.req.params.name

...

app.get '/Image/:name'    , (req, res)-> new Help_Controller(req, res).redirect_Images_to_GitHub()
```

Looking at the code there is really no way the url **http://beta.teammentor.net/TMContent/Lib_Docs/master/_Images/asd** could had been created by the code shown above

I think this is IIS doing the rewrite, @roman87 can you look into it?

**Comment by roman87** [comment]
This is fixed.

**Comment by roman87** [comment]
The issue was that IIS was rewriting redirects. So any link pointing to github was being re-written to point back to the beta server. This was temporarily fixed by  disabling the redirect re-write using:
 IIS -> Application Request Routing Cache -> Server Proxy Settings and unchecking  the "Reverse rewrite host in response headers" box. (found here: http://stackoverflow.com/questions/4243959/iis-reverse-proxy-with-rewrites-cant-handle-a-redirect-from-the-server-we-proxy) 

However, we need a more permanent solution described here: https://github.com/TeamMentor/TM_4_0_Design/issues/664
