### ISSUE TITLE
Change signature on email

### ISSUE THREAD

**Issue by afollett** [TeamMentor/TM_4_0_Design#598]
The initial sign up email is signed "Sent by Teammentor". Might be better to sign it "The TeamMentor Team" or something similar.

![team](https://cloud.githubusercontent.com/assets/4615837/6717644/5267dcc2-cd6b-11e4-9e02-6d8b2e4a85ad.jpg)

**Comment by roman87** [comment]
This is actually configurable in the backend. @michaelhidalgo can we change the default?

**Comment by michaelhidalgo** [comment]
The footer note can be changed in TBOT  (Secret Data configuration).
@roman87 , can you please update it here https://beta35.teammentor.net/teamMentor since I'm not an admin and I can't access Tbot.

![screen shot 2015-03-25 at 12 05 42 pm](https://cloud.githubusercontent.com/assets/1732035/6831617/12a722f6-d2e7-11e4-9665-aa4daa49a574.png)

**Comment by michaelhidalgo** [comment]
@DinisCruz  can you please review it and merge it? 
https://github.com/TeamMentor/Dev/pull/174

**Comment by roman87** [comment]
I merged it and assigned to myself to test.

**Comment by DinisCruz** [comment]
cool, nice changes

**Comment by roman87** [comment]
Yep, nicely fixed.

**Comment by roman87** [comment]
Will follwow up with @afollett once this is in Beta.

**Comment by romichg** [comment]
This is fixed.
