### ISSUE TITLE
Simultaneous searches leads to a database lock/in use

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#604]
If you are searching for SQL Injection, and press the search button several times (4 or 5) at the same time, you will come up with the search not being performed.

When you look at the logs, there is an entry that states that the GraphDb in in use. I also reproduce it in the beta site : 

Note that the simultaneous request where performed at the same time : 

![screen shot 2015-03-19 at 12 59 19 pm](https://cloud.githubusercontent.com/assets/1732035/6738464/e066da06-ce37-11e4-9df8-b6a499198393.png)

**Comment by DinisCruz** [comment]
Yeah, It's time to sort this out.

I'm going to add a 'retry' step which will try to 'open' the db a coupe times before 'giving up'

**Comment by DinisCruz** [comment]
this is now done see https://github.com/TeamMentor/TM_4_0_Design/issues/504#issuecomment-86754100

**Comment by roman87** [comment]
@michaelhidalgo can you give this a load and see if it is fixed?

**Comment by roman87** [comment]
As you can see from comment https://github.com/TeamMentor/TM_4_0_Design/issues/504#issuecomment-86958522 this is not fixed. @michaelhidalgo  maybe your script would pinpoint more exact number of simultaneous requests that cause the problem.

**Comment by DinisCruz** [comment]
well the main issue is fixed, I don't think you can manually reproduce the prob (specially when the cache is enabled) , and unless somebody is DoS the TM side, we shouldn't have users hitting this scenario (that said we should add monitoring for it)

**Comment by michaelhidalgo** [comment]
I agree.
I actually generated more than 100,000.00 request with cache enabled and I
do not get the error. I'll come up with a script to request random urls
just in case

2015-03-28 6:20 GMT-06:00 Dinis Cruz <notifications@github.com>:

> well the main issue is fixed, I don't think you can manually reproduce the
> prob (specially when the cache is enabled) , and unless somebody is DoS the
> TM side, we shouldn't have users hitting this scenario (that said we should
> add monitoring for it)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/604#issuecomment-87217867>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by DinisCruz** [comment]
Now that I pushed #641 it should be even harder to get a error page when a valid page is requested (note that even if the GraphDB return a 'busy result', with the #641 fix, if the data is already cached then the cached value will be used (instead of returning an 503 error)

**Comment by roman87** [comment]
It  would be nice to see the results of the test. My concern is that if we don't hit the cache, at 10 simultaneous requests we lock the db. Which basically means 10 people should be searching for something not in cache. 

As far as somebody DOSing the TM, we should be resilient to that :) "unless somebody is DoSing" is such a typical dev answer :). Yes somebody will try to DoS TM.

**Comment by michaelhidalgo** [comment]
:), @DinisCruz is this fix merged into Dev or is it on a separate branch? I would like to test it again. It seems like with ApacheBench (ab), there is a way to send different request from a text file. I will come up with this scenario

**Comment by roman87** [comment]
So lets see if we can get the number of simultanious requests needed for DB to lock using:
One random word for each request
Two random words for each request
Five random words for each request

One random character set  between 3-7 letters (i.e. not a word) 

Also when we actually hit the condition, what happens if you make a request from a web page (i.e. what is the user experience when we lock the DB)

**Comment by DinisCruz** [comment]
@michaelhidalgo code is on dev

yeah, let's find out those limits. The cache should actually mean that:
a) if the item requested is in the cache, the answer should arrive quite quickly (due to node's async model).
b) if the search needs to hit the db for mappings (which happens the first time there is a unique search), that request will be queued for execution when the db is available.
c) there are a couple places where I can optimised/cache some more mappings, which will be easier to identify once we have a nice 'hit TM with lots of traffic' script/test

One workflow we should add to this test is to track how long valid requests take when the DB is under heavy load (i.e. how much traffic/requests we need to send to start affecting normal user requests and peek the CPU)

**Comment by DinisCruz** [comment]
I think we should close this issue and open a new one focused on mapping the DoS limits of 4.0

**Comment by michaelhidalgo** [comment]
I agree. As per my tests, I have not seen the lock happening lately.

**Comment by roman87** [comment]
Ok agreed. closing
