### ISSUE TITLE
Each selected filter should have its own badge. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#605]
right now filters are just added to the badge. 

![selection_161](https://cloud.githubusercontent.com/assets/1326120/6744797/270567b0-ce84-11e4-9a51-39ac4eec5be0.png)

**Comment by DinisCruz** [comment]
@roman87 can you take a look at the code in [Issue_605_Filters_Badges](https://github.com/TeamMentor/TM_4_0_Design/tree/Issue_605_Filters_Badges) branch (the GraphDB should stay on master)

This is what it looks like

**On Index**

**Comment by DinisCruz** [comment]
I just pushed a little fix that adds a space between badges (which looks better)

![image](https://cloud.githubusercontent.com/assets/656739/6752758/fb18ed86-cf08-11e4-8c79-650c1fee7fe1.png)

**Comment by michaelhidalgo** [comment]
It looks really nice!

**Comment by roman87** [comment]
Looks like I am having some issues with the filters aligning:
![selection_162](https://cloud.githubusercontent.com/assets/1326120/6760016/3a28250c-cf1b-11e4-89af-db6e21d1b5a4.png)

**Comment by roman87** [comment]
@luchia can you take a look.

**Comment by DinisCruz** [comment]
@luchia the code that needs the ui fix is the one at https://github.com/TeamMentor/TM_4_0_Design/blob/Issue_472_Multiple_Filters/source/jade/_mixins/search-mixins.jade#L140-L163

```jade
mixin filters-div
    if filters
        #filters
            .bg
                h3 Filter by
                for filter in filters
                    h4.label= filter.title
                    table.nav
                        for result in filter.results
                            tr
                                if activeFilter
                                    if activeFilter.ids.contains(result.id)
                                        td
                                            b= result.title
                                            span.right.badge= result.size
                                    else
                                        if result.size > 0
                                            td
                                                a(href=href + '/' + activeFilter.filters + ',' + result.id)= result.title
                                                    span.right.badge= result.size
                                else
                                    td
                                        a(href=href + '/'+result.id)= result.title
                                            span.right.badge= result.size
```

**Comment by DinisCruz** [comment]
@luchia can you reapply your commit (or re-apply the css changes) to the commit that is currently on your **lucy** branch?

That branch you did the changes (Issue_605_Filters_Badges) was already out of date with your latests changes, and when I merged your fix I had a conflict with previous changes you did

**Comment by DinisCruz** [comment]
For reference I just tried to apply your https://github.com/TeamMentor/TM_4_0_Design/commit/5e07014a77831f5d3a57795e8ca542008a027c71 commit just as a patch (to latest **dev** / **lucy** branch) and had this conflict

![image](https://cloud.githubusercontent.com/assets/656739/6772151/46a1e582-d0ee-11e4-8c13-8ad0f120325f.png)

**Comment by luchia** [comment]
Mobile > Desktop

![screen shot 2015-03-24 at 9 28 22 am](https://cloud.githubusercontent.com/assets/4547737/6792827/59b3c80a-d208-11e4-849b-5662af598a07.png)
![screen shot 2015-03-24 at 9 28 26 am](https://cloud.githubusercontent.com/assets/4547737/6792828/59d8e090-d208-11e4-8c78-73fcfe2556c5.png)
![screen shot 2015-03-24 at 9 28 30 am](https://cloud.githubusercontent.com/assets/4547737/6792829/59e52c92-d208-11e4-8a73-9df0664bc7d2.png)
![screen shot 2015-03-24 at 9 28 33 am](https://cloud.githubusercontent.com/assets/4547737/6792831/5a043a60-d208-11e4-896c-54198b9dab25.png)
![screen shot 2015-03-24 at 9 28 34 am](https://cloud.githubusercontent.com/assets/4547737/6792830/5a040c8e-d208-11e4-82fb-8fc57efef806.png)

@DinisCruz and I are having some weird issues with my filters that we haven't fixed yet but I wanted to get this finished, so that's why they currently have filler text in the active filter divs. Assigning to @DinisCruz to finish off.

**Comment by luchia** [comment]
Also, the way to get this to work (quickly) was to double up my code. @DinisCruz if you can see anyway I can compress that, can you please point it out? I sat for half an hour trying to come up with a better solution code-wise but no luck.

**Comment by luchia** [comment]
So @DinisCruz had this issue -

![screen shot 2015-03-24 at 00 07 01](https://cloud.githubusercontent.com/assets/4547737/6793828/eb2b9e18-d215-11e4-8009-282ff94487fe.png)

Which I couldn't recreate on  my machine. I added a couple of small changes that should make the filters break a little better though.

![screen shot 2015-03-24 at 11 05 01 am](https://cloud.githubusercontent.com/assets/4547737/6793834/19c8f46e-d216-11e4-8d71-cc618dacf774.png)
![screen shot 2015-03-24 at 11 05 05 am](https://cloud.githubusercontent.com/assets/4547737/6793835/19f9f7f8-d216-11e4-8980-546ca9cd5260.png)
![screen shot 2015-03-24 at 11 05 11 am](https://cloud.githubusercontent.com/assets/4547737/6793836/1a26e5f6-d216-11e4-8a18-7e1879ac919f.png)
![screen shot 2015-03-24 at 11 06 27 am](https://cloud.githubusercontent.com/assets/4547737/6793839/1a881b8c-d216-11e4-8062-2d6553c078d1.png)
![screen shot 2015-03-24 at 11 06 31 am](https://cloud.githubusercontent.com/assets/4547737/6793837/1a87116a-d216-11e4-8805-38b695cbddd6.png)
![screen shot 2015-03-24 at 11 06 34 am](https://cloud.githubusercontent.com/assets/4547737/6793840/1a88cc6c-d216-11e4-9f12-5ff4fcb23f17.png)
![screen shot 2015-03-24 at 11 06 37 am](https://cloud.githubusercontent.com/assets/4547737/6793838/1a882442-d216-11e4-8ac0-80b1e389e542.png)

I did also try and build a different solution with columns, but it didn't work anywhere near as nicely as this one does.

**Comment by DinisCruz** [comment]
@roman87 since lucy is still going to need a bit more time to get this fully right, I think we should push the version that is currently on dev

that version is the one that you can see on the screenshots above. and although it has a couple issues, it already is much better than what is currently on beta.teammentor.net

**Comment by DinisCruz** [comment]
@roman87 latest version of this fix looks good, and since all tests are passing this code is now on dev and master

![image](https://cloud.githubusercontent.com/assets/656739/6799453/e2126d50-d20d-11e4-861f-a14589c8b9e8.png)

Let me know if is good with this release and I'll tag it with CR.Beta.3 (on https://github.com/TeamMentor/TM_4_0_Design/releases)

@michaelhidalgo can you give it a test drive too?

**Comment by roman87** [comment]
Yes this looks good. Closing.

Regarding pushes on Mondays. I prefer quality over quantity. If we have bugs that needs fixing, its ok if we do the push on Tuesday instead.
