### ISSUE TITLE
Wire up Index and Search Flare pages. 

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#618]

**Comment by roman87** [comment]
closing as dupe of #724

**Comment by roman87** [comment]
Oops, closed the wrong one :)

**Comment by DinisCruz** [comment]
This is kinda done, because we have these pages wired (i.e. the content is reaching them and the changes needed are view specific)

What I'm working on now is to add the AngularJS part (as in https://github.com/TeamMentor/TM_4_0_Design/issues/885) which will introduce the Javascript components and allow the development of the other issues currently marked as P0

**Comment by romichg** [comment]
This is done when I can show them to users.

**Comment by romichg** [comment]
This is done.
