### ISSUE TITLE
Consolidate icons into TM typeface

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#634]
I completely agree with @luchia on her comment at https://github.com/TeamMentor/TM_4_0_Design/issues/574

> One thought I've had is that maybe we should look at doing our own icon set. We currently have upwards of 250 icons attached to our application, of which we use roughly 20. It's nice to have options, but it is excess code in our stylesheets. If we created our own typeface set, we could take icons from wherever we like (eg. some from Bootstrap, some from Foundation, some from other locations) and create the one set that really represents the supporting text.

This will make it easier to keep a consistent fell for all icons and reduce the amount of files/css/icons we need to load

_________

EDIT BY LUCY: Adding checklist to this so it's easy to track -

I've seperated the icons into two different types - ones that are able to be more creative and ones that need to be simple. The ones that are able to be more creative:

- [x] Fix vulnerabilities
- [x] Reduce vulnerabilities
- [x] Expand knowledge
- [x] Delivers compliance
- [x] Integrates
- [x] Stores and cross-references
- [x] Provides guidance

The other icons, which are only going to appear in the application and need to be very simple, are the following:

- [x] Footer Email
- [x] Footer Twitter
- [x] Footer TOC
- [x] Button 'Start your free trial'
- [x] Button 'See for yourself'
- [x] Search icon
- [x] Index icon
- [x] Docs icon
- [x] Logout icon
- [x] Contact team icon
- [x] Filter / Technology / Web Application icon
- [x] Filter / Technology / All icon
- [x] Filter / Technology / C++ icon
- [x] Filter / Technology / iOS icon
- [x] Filter / Technology / Android icon
- [x] Filter / Technology / Java icon
- [x] Filter / Technology / .NET icon
- [x] Filter / Technology / Scala Play icon
- [x] Filter / Technology / PHP icon
- [x] Filter / Technology / HTML5 icon
- [x] Filter / Type / Guideline icon
- [x] Filter / Type / Checklist Item icon
- [x] Filter / Type / How To icon
- [x] Filter / Type / Code Example icon
- [x] Filter / Type / Vulnerability icon
- [x] Filter / Phase / Deployment icon
- [x] Filter / Phase / Design icon
- [x] Filter / Phase / Implementation icon
- [x] Filter / Phase / Test icon
- [x] Flare - Filters Icon
- [x] Flare - Save Icon
- [x] Flare - Share Icon
- [x] Flare - Trash Icon
- [x] Flare - Saved Articles Icon

**Comment by roman87** [comment]
Can't have two actions :)

**Comment by luchia** [comment]
I've seperated the icons into two different types - ones that are able to be more creative and ones that need to be simple. The ones that are able to be more creative are on the landing page:

- [ ] Fix vulnerabilities
- [ ] Reduce vulnerabilities
- [ ] Expand knowledge
- [ ] Delivers compliance
- [ ] Integrates
- [ ] Stores and cross-references
- [ ] Provides guidance

The other icons, which are only going to appear in the application and need to be very simple, are the following:

- [ ] Footer telephone
- [ ] Footer Email
- [ ] Footer address
- [ ] Footer twitter
- [ ] Footer TOC
- [ ] Filters Guideline
- [ ] Checklist Item
- [ ] How To
- [ ] Code Example
- [ ] Button 'Start your free trial'
- [ ] Button 'See for yourself'
- [ ] Search icon
- [ ] Index icon
- [ ] Docs icon
- [ ] Logout icon
- [ ] Contact team icon
- [ ] Filters Technology Independant icon
- [ ] Filters Technology icons

I need to finish updating the full application list of icons (technology icons) as they should be apart of the typeface as well. I also haven't even look at Flare yet and what icons we use in that that don't appear in Jade. For the moment, Jade is a good place to start.

**Comment by luchia** [comment]
I started sketching out ideas for the creative icons and will begin rendering these at some point today -

![img_0080](https://cloud.githubusercontent.com/assets/4547737/6958987/c811aba0-d956-11e4-9df5-b1138f1a24c6.jpg)
![img_0081](https://cloud.githubusercontent.com/assets/4547737/6958986/c8109026-d956-11e4-83b3-639df3911238.jpg)
![img_0082](https://cloud.githubusercontent.com/assets/4547737/6958988/c8134992-d956-11e4-9530-1e1c485e828d.jpg)

**Comment by DinisCruz** [comment]
cool, I like this a lot :)

**Comment by michaelhidalgo** [comment]
Yes I agree, it looks pretty cool.

2015-04-02 6:44 GMT-06:00 Dinis Cruz <notifications@github.com>:

> cool, I like this a lot :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/634#issuecomment-88885731>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by luchia** [comment]
First version of 'Fix vulnerabilities' icon -

![screen shot 2015-04-03 at 11 00 43 am](https://cloud.githubusercontent.com/assets/4547737/6976709/d22413f4-d9f0-11e4-8206-a8af3c72c0dd.png)

This is the first icon on the landing page icon that represents this text:
> Fix vulnerabilities quicker than ever before with TEAM Mentor's seamless integration into a developer's IDE and daily workflow.

**Comment by pjenney58** [comment]
I like the circle …

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by tekgirl77** [comment]
I like the square and the circle... I guess my preference depends on what
the other 2 icons will look like on that page.

They look very cool!


Salle Ingle
Support & Implementation Specialist, eLearning
[image: https://www.securityinnovation.com/_img/art/logo.png]

**Comment by roman87** [comment]
So some of my 5c. 
Expand knowledge icon associates with callosotomy :). sorry, I have vivid imagination :). but that is just me. What if you try the expanding universe, or galaxy? Somewhere we make a reference to the galaxy of knowledge. Or maybe just use less gray matter in the picture :)
Also what about something simple like IQ+?

Provides guidance associates with a homeless guy :). What about something like a "tour guide" or a traffic cop, a school crosing guard, a teacher, coach, a map, (especially since we have an idea of the map in the CC). Or maybe simply car lane markings?

Love the delivers compliance. Love the fix vulnerabilities (sketch).  Maybe 'integrates" could use double twist instead of singe. 

In the first version of the "fix vulnerability" - the lamp, implies long hours. Which is not the message we want to send, the pencil cup looks too much like coffee, which implies long hours as well. Also perhaps we want to make the suggestion that vulnerability is already fixed by putting a little checkmark next to the screw-driver.  I personally think though that the composition is too busy for an Icon.  If we go with busy than add a chair, swiveled sideways, implying that the dude has left to play football already because vulnerability was fixed.

**Comment by DinisCruz** [comment]
on the 'icons being busy' I quite like the path @luchia is going, 

In a way (from a design point of view) we’re such a plain company. Most of our icons look like we bought them off icon-finder (or are using default css icon libraries). I think these add personality to what we’re doing. It looks like we care enough to hire a designer to design an icon set (which we do)

let's give @luchia space to create a full set and then see which ones could be tweeaked

**Comment by roman87** [comment]
I am sure @luchia put the work here for comments, not as a request for space. I think constructive comments is important early in the cycle.

**Comment by luchia** [comment]
I'm definitely open to feedback. I did try to go simple like my sketches @roman87 but it wasn't really doing it for me -

![screen shot 2015-04-03 at 8 14 39 am](https://cloud.githubusercontent.com/assets/4547737/7015078/4f63819c-dd11-11e4-80f8-456a1dc02898.png)

I was then thinking about the email thread talking about the competitor analysis last week and how we could differentiate from our competition. Coffee doesn't necessarily have to mean long hours, nor does the lamp. I was thinking it was more of a 'work-from-home' situation in the icon for a number of reasons including the computer being a laptop. But it's just different perspectives, everyone has their own idea of what things mean. Thinking about that lead me to the following -

##### Fix vulnerabilities
![screen shot 2015-04-07 at 11 01 34 am](https://cloud.githubusercontent.com/assets/4547737/7015420/efbef77a-dd16-11e4-8cc8-7620a4034d2b.png)

##### Reduce number of vulnerabilities
![screen shot 2015-04-07 at 11 01 49 am](https://cloud.githubusercontent.com/assets/4547737/7015419/efbe40c8-dd16-11e4-9ec0-f3f61de4f1dc.png)

##### Expand knowledge and improve process
![screen shot 2015-04-07 at 11 11 43 am](https://cloud.githubusercontent.com/assets/4547737/7015421/efcfb592-dd16-11e4-8253-57dd73512a0c.png)

You know that I'm normally open to feedback and try to take onboard what everyone says about my work so I can improve. I really, really like these though and I think they do give us character and personality. The application icons aren't going to be this creative or have as much stuff going on, they're going to be similar to what we have now. 

I thought while I had the opportunity to be creative, I should try to create icons that represent as much as the text as possible and tell our story. I think they're awesome and I don't often think that about my work.

**Comment by roman87** [comment]
Exactly because we have room to be creative here, we need to make sure we embed correct symbolism. Symbols are extremely important in our society and cause us to make subconscious decisions (where all decisions are made). Here is an experiment I recently read about: participants were in a room, divided 50/50.  Each person in group 1 was given $10. They had to give some of that cash to another person from the other group. They both got to keep the money iff the other person agreed to take it. So if there was a backpack somewhere in the room, most offered $5 to the other participant. If there was a briefcase in the room, most offered $2-3 to the other participant. 
When meeting a person for the first time, if you hold a warm drink, you a perceived as a warmer person. 
We also need to focus on the message we want to portray. Work from home, has nothing to do with the product we are selling :) 
Anyways, just some fun facts so you know why I think its really important not to get it wrong.
So, I like the "Fix vulnerabilities" except for the red cross in one of the lines. It creates a conflict with the theme. I am not sure what pencil cup symbolizes. But it seems in place.
I don't like "Reduce number of vulnerabilities" Maybe make the line straight instead? 
I like the last one. Maybe putting arrows showing expansion of the light bulb (instead of a lighting thing) will drive the "expanded" part better.

**Comment by DinisCruz** [comment]
I quite like what @luchia is doing here, she is having a good feel for it, and I agree that they look really cool

Also let's not get to hang on the details since some of them will not be THAT visible. @luchia can you post some of icons in the size that we will be using them?

**Comment by roman87** [comment]
Look, @luchia is a Professional Designer. With a capital D.

*B*e*i*n*g* this makes it it is extremely important to get the details, no matter how small, right. They are the difference between someone han*gi*ng on you*r* site *l*ong enough to engage your brain and actually *read* what is being offered, and maybe take it for a spin, and  moving down the list of search results. 

Watch this on the power of this: https://www.youtube.com/watch?v=befugtgikMg

**Comment by DinisCruz** [comment]
that is why I was saying that we should go with @luchia opinion

**Comment by roman87** [comment]
That is why she shares her work to get oppinions that matter.  It takes a TEAM to make a Mentor :)

**Comment by luchia** [comment]
Some revisions after our discussion in the meeting this morning -

##### Fix vulnerabilities
I removed the cup of pencils but I like it better with it because I think it makes it seem more realistic and the asymmetry of the icon looks better than it being perfectly balanced in my opinion.

![screen shot 2015-04-08 at 12 23 32 pm](https://cloud.githubusercontent.com/assets/4547737/7037838/69f9524e-ddec-11e4-9bc3-4b3e1143de2e.png)
![screen shot 2015-04-08 at 12 24 01 pm](https://cloud.githubusercontent.com/assets/4547737/7037839/6a02397c-ddec-11e4-8ae9-cedbebcd6c78.png)

##### Reduce vulnerabilities
I tried a straight graph but I honestly prefer the more realistic verison of the graph which shows fluctuations -

![screen shot 2015-04-08 at 11 06 37 am](https://cloud.githubusercontent.com/assets/4547737/7037854/a1a75b46-ddec-11e4-8ce2-7eb1d7b4be4e.png)
![screen shot 2015-04-07 at 11 01 49 am](https://cloud.githubusercontent.com/assets/4547737/7015419/efbe40c8-dd16-11e4-9ec0-f3f61de4f1dc.png)

##### Expand knowledge and improve process
I tried some of your ideas @roman87 and even a few of my original ideas involving brain power and knowledge represented through the brain and couldn't really get it to work. I still prefer my original on this one -

![screen shot 2015-04-08 at 12 29 57 pm](https://cloud.githubusercontent.com/assets/4547737/7037873/fb63f626-ddec-11e4-96f8-7d0f07ab01c0.png)

I just pushed some work to the branch Issue_634 and if you go to the POC pages, you'll be able to see the icons in action. This is just a quick prototype but if everyone thinks I should continue, I would tidy up alignment and obvious issues.

![screen shot 2015-04-08 at 1 18 22 pm](https://cloud.githubusercontent.com/assets/4547737/7038227/eaf015d6-ddf1-11e4-80fb-c776e0229b7b.png)
![screen shot 2015-04-08 at 1 18 25 pm](https://cloud.githubusercontent.com/assets/4547737/7038226/eaefde7c-ddf1-11e4-9812-c7be6bc7f05f.png)
![screen shot 2015-04-08 at 1 18 29 pm](https://cloud.githubusercontent.com/assets/4547737/7038228/eaf0a848-ddf1-11e4-873d-10cbd79a02ac.png)
![screen shot 2015-04-08 at 1 18 32 pm](https://cloud.githubusercontent.com/assets/4547737/7038231/eaf2cd62-ddf1-11e4-97a9-e99c4ad48ee3.png)
![screen shot 2015-04-08 at 1 18 35 pm](https://cloud.githubusercontent.com/assets/4547737/7038229/eaf1f2ac-ddf1-11e4-97cf-262abfb089c6.png)
![screen shot 2015-04-08 at 1 18 38 pm](https://cloud.githubusercontent.com/assets/4547737/7038230/eaf20e4a-ddf1-11e4-8d2f-fb33ab1380af.png)

**Comment by roman87** [comment]
Yea  the straight line doesn't really work and green arrows ether. 


![selection_177](https://cloud.githubusercontent.com/assets/1326120/7054417/44b01586-de0a-11e4-9efc-7870c3b5590a.png)
 
I don't know if it is supposed to be like this, but on my screen they are quite large:

**Comment by luchia** [comment]
So I'm really happy with the first sets but still not satisfied with the last one. I will work on it early Monday morning so we have something for release. I will need everyone to weigh on which structure you like (the list items vertical or horizontal) and which set of icons (round, rect or none).

You can find these pages in the POC directory on the branch Issue_634. Thank you.

**Comment by DinisCruz** [comment]
nice, send it a PR when your happy,

It would be cool to add this to next week's beta

**Comment by roman87** [comment]
1 vote for vertical
1 vote for round 
:)

**Comment by luchia** [comment]
I had a minor mishap this morning when I realised that all my photoshop files were/are gone from my computer. Thankfully, we had production ready png's in the application and my code was on Github so I was able to retrieve PNGs for Jade at the very least. From these, I will need to remake the Photoshop files but it should simply be a matter of selecting and filling all of the shapes with colour, not having to redraw every single shape. 

Below is a gif of testing the icon sprite that I made in three browsers - Chrome, Safari and Firefox -

![icons](https://cloud.githubusercontent.com/assets/4547737/7127370/7cd5fd56-e286-11e4-8a07-b359eca6d22f.gif)

I've sent a pull request for @DinisCruz.

**Comment by luchia** [comment]
Here's the [PR](https://github.com/TeamMentor/TM_4_0_Design/pull/693) @DinisCruz.

**Comment by luchia** [comment]
Update re missing icons - all my ongoing work will be stored in the What's Cookin' repo (the specific directory can be found [here](https://github.com/TeamMentor/WhatsCookin/tree/master/TEAM%20Mentor%20(Lucy)/Landing%20Page%20Icons)). We're now back up to date and I'm going to start working on the Features pages icons now.

**Comment by DinisCruz** [comment]
you really need to have an auto backup for your photoshop files

what about dropbox, that should work?

**Comment by DinisCruz** [comment]
merged and added to https://github.com/TeamMentor/TM_4_0_Design/issues/675

**Comment by DinisCruz** [comment]
and it looks like this locally 

![image](https://cloud.githubusercontent.com/assets/656739/7133723/142dba2a-e28e-11e4-91ff-1abe6c863652.png)

**Comment by luchia** [comment]
I don't want Dropbox on my machine for privacy reasons. I've set up a workflow now so this doesn't happen again.

**Comment by DinisCruz** [comment]
sure, sounds good

**Comment by luchia** [comment]
Here's two more. These are super rough because I've been spending a lot of time on Flare this last week. Feel free to throw in ideas for setting the scene in these icons, I honestly haven't had too much time to spend on them the past week (and it's obvious).

![delivers-compliance](https://cloud.githubusercontent.com/assets/4547737/7174591/d39fcc0c-e44d-11e4-923b-3da2acf915e6.png)

> Delivers compliance-specific secure coding guidance for PCI-DSS, OWASP Top 10, CWE and other popular frameworks.

![integrates](https://cloud.githubusercontent.com/assets/4547737/7174592/d3a08822-e44d-11e4-9ffb-305015c6ae11.png)
> Integrates with multiple static analysis tools and developer environments (IDE’s) to map prescriptive coding guidance to scan results to fix vulnerabilities.

I'd really like to get the last two of these out before the end of the week, but not sure if I'll be able to. We'll see.

**Comment by luchia** [comment]
Further work -

![delivers-compliance](https://cloud.githubusercontent.com/assets/4547737/7261630/a119b08c-e8b6-11e4-837a-6291695946b4.png)

> Delivers compliance-specific secure coding guidance for PCI-DSS, OWASP Top 10, CWE and other popular frameworks.

![integrates](https://cloud.githubusercontent.com/assets/4547737/7261632/a11bdf74-e8b6-11e4-96f4-c21c1035c06d.png)

> Integrates with multiple static analysis tools and developer environments (IDE’s) to map prescriptive coding guidance to scan results to fix vulnerabilities.

![stores-crossreferences](https://cloud.githubusercontent.com/assets/4547737/7261633/a11cd99c-e8b6-11e4-9ed8-31a6b0dd23ef.png)

> Stores and cross-references your security policies with out-of-the-box secure coding checklists and examples.

![provides-guidance](https://cloud.githubusercontent.com/assets/4547737/7261631/a11bea8c-e8b6-11e4-8fc9-9bac297b06ef.png)

> Provides guidance to assist developers in reducing security vulnerabilities in software applications.

**Comment by luchia** [comment]
We have a completed set of landing page icons -

![completedset](https://cloud.githubusercontent.com/assets/4547737/7284412/b830fff8-e980-11e4-9d99-7d4cafc8bab7.png)

**Comment by DinisCruz** [comment]
Looks good to me.

Once you are happy with them, can you update the https://github.com/TeamMentor/TM_4_0_Design/wiki/TM-Custom-Icons wiki page with details about each one?

**Comment by luchia** [comment]
Here's my altogether finals, I'd like to hear from @michaelhidalgo @tekgirl77 @roman87 before updating the wiki (but I will once I do).

![completedset3](https://cloud.githubusercontent.com/assets/4547737/7306274/7022137e-ea47-11e4-9f94-043b31921e90.png)

**Comment by luchia** [comment]
Rough version of 9/26 application icons. I quickly made these and put them all in a document together so I can make them look as if they are a part of a set -

![set](https://cloud.githubusercontent.com/assets/4547737/7307411/0981e546-ea50-11e4-994d-6cad9aeadec4.png)

**Comment by tekgirl77** [comment]
I like them @luchia .  I think the more complex ones could look too busy or over-used.  I like the mixture of the final set.  I like the bug better on the magnifying glass in this last set also.  :)  I like the shading that was added.  I like the folder that was added to the papers icon.  I definitely like the direction you're going with them!  Again, I think I'd have to see them on some contextual page samples to have more of an opinion... once we see them on the pages, I think we'll have more firm and immediate favorites.

**Comment by roman87** [comment]
I think they all look great. I actually like the worm better than the bug :), but I think it doesn't matter. My only few comment  are
- I think the checkboxes should be checked. Otherwise its not really clear its a checklist
- The arrows next to the skull and shield look really bleak on my screen, so the skull actually stands out more. Maybe make the arrows darker a bit and maybe move the skull down and shield up (i.e. switch places). Also what about making the skull subtly smaller than the shield. Barely noticeably smaller. This is just a thought. It will be disproportional but barely seen.

**Comment by luchia** [comment]
I'm actually thinking the more simpler set is going to be the way to go, especially given how small the icons are on the screen. The details get missed -

![screen shot 2015-04-28 at 11 50 43 am](https://cloud.githubusercontent.com/assets/4547737/7361527/3dec4902-ed9d-11e4-9eaf-002aa8094cd3.png)
![screen shot 2015-04-28 at 11 50 46 am](https://cloud.githubusercontent.com/assets/4547737/7361528/3e549a20-ed9d-11e4-83a0-9c8b54963ae7.png)

I did a POC page for each to show what the other set would look like and I think that's -

![screen shot 2015-04-28 at 11 42 20 am](https://cloud.githubusercontent.com/assets/4547737/7361535/54ea7728-ed9d-11e4-8dd1-b1c99e8a58c4.png)
![screen shot 2015-04-28 at 11 49 31 am](https://cloud.githubusercontent.com/assets/4547737/7361536/54eca1b0-ed9d-11e4-8720-fbe241f9ff44.png)

**Comment by pjenney58** [comment]
Ya know,  I’m really starting to like the way this looks …

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by DinisCruz** [comment]
@pjenney58 thx, the new version will be included in this [week's release](https://github.com/TeamMentor/TM_4_0_Design/issues/719) and should be live in the next couple days

**Comment by luchia** [comment]
Application icons for Jade are complete -

![set](https://cloud.githubusercontent.com/assets/4547737/7403486/84b76268-ef19-11e4-8ab0-553f124851f8.png)

I need to make this a typeface file and then insert them in place of the Foundation icons currently included. I should have this done by the end of the week, max (ready for the next release!)

**Comment by luchia** [comment]
Yay, they're in the application!!!

![screen shot 2015-04-30 at 4 30 24 pm](https://cloud.githubusercontent.com/assets/4547737/7409094/da3928b4-ef66-11e4-9a04-d8bd29fd0edd.png)
![screen shot 2015-04-30 at 4 30 26 pm](https://cloud.githubusercontent.com/assets/4547737/7409093/da3900e6-ef66-11e4-8690-41d211c556b4.png)

Had to test them on another page because my build is broken at the moment. Will finalise this tomorrow once I have it fixed.

**Comment by tekgirl77** [comment]
These look amazing Lucy!  I love them!

**Comment by luchia** [comment]
Thank you!!!

**Comment by pjenney58** [comment]
This looks great!

I’m still confused as to why “C” isn’t represented in the list though :-)

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by luchia** [comment]
It is -

![screen shot 2015-05-01 at 8 32 08 am](https://cloud.githubusercontent.com/assets/4547737/7423791/950af850-efdc-11e4-86e0-c7383f5b803f.png)

Perhaps i should move the plus plus so it's more obvious the C is a C?

**Comment by pjenney58** [comment]
That’s cool but I think it needs to be C/C++ or they need to be separate.  Two completely different problem sets.

Cheers!

pete.;1


---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney
VP, Strategic Initiatives
Ombudsman

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by luchia** [comment]
Oh okay, you mean why is C not in the filter list? I'm not actually sure - maybe @DinisCruz or @roman87 know why.

**Comment by pjenney58** [comment]
Yes, that's the question.  C is the worst offender in The software security 'scape and needs direct representation.  I guess my mantra would be, if I actually had one, would be "'new' is not the same as 'malloc'." Hey, maybe we could have t-shirts made?  😀

Cheers!
 
pete.;1

---)----------------------------
Security Innovation, Inc.
Peter H. Jenney
Vice President of Strategic Initiatives
(office)   +1.978.694.1008 x164
(mobile) +1.603.264.3961
(skype)     PeteJenney

**Comment by luchia** [comment]
What the icons actually look like in the application -

![screen shot 2015-05-01 at 11 37 54 am](https://cloud.githubusercontent.com/assets/4547737/7425618/6a55da56-eff7-11e4-865e-868239dd08e0.png)
![screen shot 2015-05-01 at 11 43 56 am](https://cloud.githubusercontent.com/assets/4547737/7425620/6a866554-eff7-11e4-8768-7381cc5df250.png)
![screen shot 2015-05-01 at 11 44 07 am](https://cloud.githubusercontent.com/assets/4547737/7425619/6a8501f0-eff7-11e4-8063-d087c12bfebb.png)

These are ready to be QA'ed! I will create a PR at the end of the week with all of my work for the next release.

**Comment by roman87** [comment]
@pjenney58  C is not in the application because our content is for C++ :) Now I do agree we need specific guidance for C, but this is not what this issue is about :)

**Comment by roman87** [comment]
@luchia Icon's look great, can't wait to see them in the app.

**Comment by luchia** [comment]
Related to issue #750, here are the icons I made for the Phase filters -

![screen shot 2015-05-06 at 7 09 09 am](https://cloud.githubusercontent.com/assets/4547737/7483106/a723fadc-f3bf-11e4-8fa3-d9048d5c4270.png)

**Comment by luchia** [comment]
This issue is ready to be QA'ed on both Flare and Jade. All icons are now in both versions of the application. The following icons are in Flare only -

![screen shot 2015-05-06 at 9 42 20 am](https://cloud.githubusercontent.com/assets/4547737/7485091/57fa83f8-f3d4-11e4-97ef-47ff09e5d5a8.png)
![screen shot 2015-05-06 at 9 42 43 am](https://cloud.githubusercontent.com/assets/4547737/7485093/57fbc84e-f3d4-11e4-8650-66b5e7abb89a.png)
![screen shot 2015-05-06 at 9 42 48 am](https://cloud.githubusercontent.com/assets/4547737/7485092/57fb2e48-f3d4-11e4-840b-7c6bd0180211.png)
![screen shot 2015-05-06 at 9 42 52 am](https://cloud.githubusercontent.com/assets/4547737/7485094/58022bee-f3d4-11e4-9ee7-fac2b87cee88.png)
![screen shot 2015-05-06 at 9 42 56 am](https://cloud.githubusercontent.com/assets/4547737/7485095/5805c330-f3d4-11e4-966f-89649f6da589.png)

If and when we need more icons, I have created them in an easy to maintain way which allows us to continue to add relevant ones as we require. Changing the tag to QA and assigning to Roman for QA/closing.

**Comment by roman87** [comment]
This was a great effort. Very well done. Closing!
