### ISSUE TITLE
[Q] Normalize technique used for applying Filter icons

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#691]
@luchia can you standardise on one technique use to apply Filter icons? (once that is done @tekgirl77 can you update the test we created for https://github.com/TeamMentor/TM_4_0_Design/issues/644 ?)

As you can see by the test https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/regression-sprint-1.coffee#L368-L422  ...

![image](https://cloud.githubusercontent.com/assets/656739/7112131/8e5ece7c-e1be-11e4-8770-4e2bce17aa46.png)

... we ended up with two complete different ways to apply the icons (not only between Technology and Type, but even between different Technologies, like **All** and **Html 5**)

The fix will need to be applied to this [jade file](https://github.com/TeamMentor/TM_4_0_Design/blob/Dev/source/shared-mixins/globals.jade):

![image](https://cloud.githubusercontent.com/assets/656739/7112190/1ecc4d68-e1bf-11e4-8eb3-b0dc00ef658c.png)

**Comment by luchia** [comment]
Yup, this is essentially why we need #634. I'm working on it, hopefully I'll have something final in the next couple of weeks so we don't have the mess we have at the moment.

**Comment by DinisCruz** [comment]
lovely, it will be good to normalise those mixins

**Comment by luchia** [comment]
This has been done on my most recent push on the Lucy branch -

![screen shot 2015-04-30 at 6 31 30 pm](https://cloud.githubusercontent.com/assets/4547737/7409137/3320d1ca-ef67-11e4-81fb-d7f393aeff69.png)
![screen shot 2015-04-30 at 6 31 43 pm](https://cloud.githubusercontent.com/assets/4547737/7409136/33204610-ef67-11e4-9b80-ef856132d263.png)

There are a few small things to fix still, but this issue can be QA'ed/closed because it has been addressed.

**Comment by DinisCruz** [comment]
yap done
