### ISSUE TITLE
Alerts styling makes it hard to see (getting started pages)

### ISSUE THREAD

**Issue by afollett** [TeamMentor/TM_4_0_Design#733]
I tried to log in to beta.teammentor.net a couple of times and after 2 password changes i finally noticed the error "account expired". It was in green in the upper left corner. This message should be in red so that it is obvious to the user. 

![teammentor](https://cloud.githubusercontent.com/assets/4615837/7360277/8a9a6842-ecfd-11e4-8960-c8270764815f.jpg)

**Comment by DinisCruz** [comment]
I agree, I had the same issue the other day on 'failed login'

**Comment by luchia** [comment]
So I think this issue is more to do with the alerts not being obvious, thus making the user miss the message. @afollett, I have renamed the issue so that I can properly address this for all use cases.

**Comment by luchia** [comment]
So we now have two different types of alerts - OK and bad:

![screen shot 2015-05-01 at 10 39 27 am](https://cloud.githubusercontent.com/assets/4547737/7425178/871fdd1a-efef-11e4-832a-31580120a1fd.png)
![screen shot 2015-05-01 at 10 41 05 am](https://cloud.githubusercontent.com/assets/4547737/7425179/8720bbc2-efef-11e4-8e23-e8515ebe25e2.png)

I have assigned the CSS classes to the correct alerts in the referenced commits.

**Comment by luchia** [comment]
I will create a PR at the end of my week to include this in the next release. Once it has been merged, I will assign this to Roman for QA.

**Comment by luchia** [comment]
Couple of small changes because I think the writing was hard to read in white -

![screen shot 2015-05-01 at 11 35 09 am](https://cloud.githubusercontent.com/assets/4547737/7425575/7a8e238e-eff6-11e4-9e5a-c217334978fe.png)
![screen shot 2015-05-01 at 11 35 39 am](https://cloud.githubusercontent.com/assets/4547737/7425576/7a8e799c-eff6-11e4-8e50-dfa4f2c92854.png)


![screen shot 2015-05-01 at 11 35 09 am](https://cloud.githubusercontent.com/assets/4547737/7425565/5190be42-eff6-11e4-84b6-4404f985fc76.png)
![screen shot 2015-05-01 at 11 35 39 am](https://cloud.githubusercontent.com/assets/4547737/7425566/51c2eb2e-eff6-11e4-9ae5-8d55c5ccef5c.png)

**Comment by luchia** [comment]
This fix is in my PR referenced. I am marking this QA and assigning to Roman for QA and follow up with @afollett.

**Comment by roman87** [comment]
This looks good. I like ti.

**Comment by roman87** [comment]
Will follow up with once its in beta.

**Comment by roman87** [comment]
@afollett this has been fixed. Could you take a look at latest beta and let us know if this works the way you'd expect.

**Comment by romichg** [comment]
closing due to ttl
