### ISSUE TITLE
Fix Flare docs navigation

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#737]
It looks like this at the moment

![image](https://cloud.githubusercontent.com/assets/656739/7402027/8cd495c8-eec0-11e4-93d0-4f0ed5571d52.png)

and it is linked from the production pages

**Comment by luchia** [comment]
This has been finished on the Flare branch.

#### Mobile
![screen shot 2015-05-13 at 12 16 01 pm](https://cloud.githubusercontent.com/assets/4547737/7602622/005c43a2-f96a-11e4-8bd3-62e664141841.png)
![screen shot 2015-05-13 at 12 16 04 pm](https://cloud.githubusercontent.com/assets/4547737/7602620/00599fd0-f96a-11e4-927a-0cc998c91b3b.png)
![screen shot 2015-05-13 at 12 16 07 pm](https://cloud.githubusercontent.com/assets/4547737/7602621/005ae624-f96a-11e4-987e-7deebc8a979a.png)

#### Desktop
![screen shot 2015-05-13 at 12 16 15 pm](https://cloud.githubusercontent.com/assets/4547737/7602619/00595570-f96a-11e4-95e3-69e76f38343c.png)
![screen shot 2015-05-13 at 12 16 18 pm](https://cloud.githubusercontent.com/assets/4547737/7602623/005dc5ce-f96a-11e4-89ee-12fa70adc165.png)
![screen shot 2015-05-13 at 12 16 21 pm](https://cloud.githubusercontent.com/assets/4547737/7602624/005fd896-f96a-11e4-92e6-993f20a6ac63.png)

So as @DinisCruz and I discussed, first verison of Flare should ideally work without JS which is why this has been like it has. In future version, it'd be nice to have these accordian style.

**Comment by romichg** [comment]
Done for this issue.
