### ISSUE TITLE
Add support for "virtual articles"

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#785]
This is what is called scope creep :)

Turns out there are 22 articles that are linked to from TP that had been removed because they are duplicates. This naturally breaks the TP links. So we need to map the 22 GUIDS to the GUIDS that actually exist and should reflect the content. (@struth is working on that). But we also need a way to map those GUIDS inside the app. For now a rudimentary text file would do. 
@michaelhidalgo @DinisCruz  which one of you wants to do this?

**Comment by DinisCruz** [comment]
ok, I need that list asap

**Comment by DinisCruz** [comment]
OK, I think I found a really sweet solution for this (and the idea of having short links to articles)

Most of the capabilities were already in place, and I leveraged the power of having a GraphDB where all I had to do was to add an extra triplet mapping (and ensure it could be loaded and understood)

The way it works is that during graph loading phase, TM will load all files that it finds inside the /TM_4_0_GraphDB/.tmCache/Lib_UNO-json/Graph_Data folder

so if we add a file like this https://github.com/TMContent/Lib_UNO-json/blob/master/Graph_Data/virtual-articles.json with this content

![image](https://cloud.githubusercontent.com/assets/656739/7617886/13fe44d2-f9a6-11e4-810a-0ab1ea0c9721.png)

Then those extra mappings will also be used to resolve the article  id :)

Which means that with those triplets loaded, the following links will work:

**http://localhost:1337/article/d18c00d5-2365-45c8-bde7-000000000001**

![image](https://cloud.githubusercontent.com/assets/656739/7617963/a76fa18e-f9a6-11e4-82d7-1b317e402b94.png)

**http://localhost:1337/article/d18c00d5-2365-45c8-bde7-000000000002**

![image](https://cloud.githubusercontent.com/assets/656739/7617946/8a6dad92-f9a6-11e4-8d28-3092a2a970e4.png)

**http://localhost:1337/article/ThreatModel** (or even http://localhost:1337/a/ThreatModel )

![image](https://cloud.githubusercontent.com/assets/656739/7617934/7d46e39a-f9a6-11e4-93a7-cf240674fa23.png)

**http://localhost:1337/article/abc**

![image](https://cloud.githubusercontent.com/assets/656739/7617955/9913c21e-f9a6-11e4-97a7-202d9d95dc55.png)

@michaelhidalgo , @roman87 can you try this with the Virtual mappings from Serge?

To test this:
-  clone from https://github.com/TMContent/Lib_UNO-json
- make changes on your local copy of /Graph_Data/virtual-articles.json
- remove the 'tm-uno-loaded.flag' to indicate a db reload 
- open an ariticle (which will trigger the db reload)

Note:  I have to see what happens when the Json data is re-generated

**Comment by michaelhidalgo** [comment]
This is a nice solution.I tested with a couple of values that should resolve an article and the it worked just fine.

**Comment by roman87** [comment]
Works like a charm. 
I build the new virtual-articles.json with this
```
awk '{print "{ \"subject\": \"article-"$2"\",\t\"predicate\": \"alias\",\t\"object\": \""$1"\" },"}' va.tmp >> virtual-articles.json 
```
Cleaned up the file a bit. Tested and its all great.

I pushed the changed virtual-articles.json to to https://github.com/TMContent/Lib_Uno-jso
Lets make sure the file stays there, is not overwritten by the new json data and that it doesn't break any process.

**Comment by roman87** [comment]
Looks like virtual-articles.json stays fine within the repo. This works great.
