### ISSUE TITLE
Invisible image SSO does not work on 4.0

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#836]
TM 3.5 has an option to have an SSO link which returns an invisible image.  The image SSO link looks like this:

https://www36.teammentor.net/Aspx_Pages/SSO.aspx?userName=SSO_User&requestToken=<TOKEN>&format=img
This is currently not working  in 4.0 and needs to be used for TP integration.

@michaelhidalgo is working on the fix. Once done, @DinisCruz we need this done as a patch to current 4.0

**Comment by michaelhidalgo** [comment]
In order to fix this issue, we need to reissue the invisible gif89a from NodeJS, the original response from the SSO is not being recognized as a valid gif89a.

I tested several ways with Buffer (converting the underlaying data to binary and to base64 enconding) but it turns out that some data is lost/damaged from the original gif.

Here is an example of how the image is interpreted by the user agent  : 

![screen shot 2015-05-26 at 21 38 29](https://cloud.githubusercontent.com/assets/1732035/7828369/c31faf98-03ef-11e5-928a-fb295533fa0d.png)

**Comment by DinisCruz** [comment]
Code merged

added #840 to track the need for Unit Test

**Comment by roman87** [comment]
This is fixed
