### ISSUE TITLE
Flare needs favicon

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#873]
A number of Flare pages are missing the default icon

http://localhost:12345/flare/features
![image](https://cloud.githubusercontent.com/assets/656739/8316530/9d287a7a-19ef-11e5-8160-348ead49e8ee.png)

http://localhost:12345/flare/navigate
![image](https://cloud.githubusercontent.com/assets/656739/8316545/b0bd3576-19ef-11e5-816f-12fee668403c.png)

Note: the TM window on the other tab is from the Jade version

**Comment by luchia** [comment]
It has one, but for some reason it's not showing. I'll find out why.

**Comment by luchia** [comment]
This has been fixed by renaming the file as well as researching on SO -

![screen shot 2015-06-24 at 3 11 32 pm](https://cloud.githubusercontent.com/assets/4547737/8323113/5ded2b14-1a83-11e5-9adb-e05f0f802eee.png)

Note that it works on the same pages in other browsers -

![screen shot 2015-06-24 at 3 12 49 pm](https://cloud.githubusercontent.com/assets/4547737/8323130/8cad042e-1a83-11e5-867b-67f6db1b5439.png)

**Comment by romichg** [comment]
Done.
