### ISSUE TITLE
TEAM Mentor 4.0 breaking into Mobile too early

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#877]
I did some manual testing on SauceLabs and it seems like TM is breaking into mobile view too early here is a screenshot : 

![screen shot 2015-06-26 at 15 36 26](https://cloud.githubusercontent.com/assets/1732035/8387888/9dd99f4a-1c19-11e5-83d2-5c0e33083bee.png)

@luchia , please let me know if you need to access SauceLabs, I will be doing some more manual testing on this environments and try to automate those test.

**Comment by luchia** [comment]
I've looked into this today and found out (today) that this is because IE8 and lower does not support media queries, which makes our Jade version completely broken. This is a really big deal.  It means that we cannot have a responsive legacy browser version.

I think our best option is to have an IE8 version and an IE9 version, which then leaves Flare to cover all modern browsers.

**Comment by romichg** [comment]
Not at all. Jade is supposed to work on all browsers without different version. If IE8 does not support media queries, then we can't use them. Let talk about this on the call.

**Comment by luchia** [comment]
I meant just a stylesheet for IE8 only. This won't take long to fix.

**Comment by luchia** [comment]
@michaelhidalgo I pushed two Jade and Static a branch called Issue_877. Can you please take a look at them and test them in relation to this issue? 

Thank you.

**Comment by romichg** [comment]
@luchia this needs to be fixed! Jade is completely messed up in IE8
![selection_001](https://cloud.githubusercontent.com/assets/1326120/9887762/4d66b148-5bbf-11e5-87b7-f5c54c2c5066.png)

**Comment by luchia** [comment]
This has been re-added in (it was all on branch Issue_877 but I don't think it got merged in for some reason). Can you please test it @michaelhidalgo?

**Comment by romichg** [comment]
Can you please merge it into dev? I will give it a shot.

**Comment by luchia** [comment]
It has been merged.

**Comment by romichg** [comment]
Still an issue with IE8 You can test it with IE8 emulation mode on a Windows VM.

![selection_002](https://cloud.githubusercontent.com/assets/1326120/9952320/38e1fa72-5da2-11e5-8572-bef591100269.png)

**Comment by michaelhidalgo** [comment]
Yes it is breaking on IE 8 (from SauceLabs)

![screen shot 2015-09-17 at 23 33 11](https://cloud.githubusercontent.com/assets/1732035/9952523/0114a4a4-5d94-11e5-9b4b-63cc49821b13.png)

**Comment by luchia** [comment]
Woops, I stuffed up. Sorry guys, [this is why](http://stackoverflow.com/questions/5769493/ie8-support-for-css-media-query).

> // if lte IE 8
>    link(rel='stylesheet', type='text/css', href='/css/jade-legacy-stylesheet.css')
>    link(href="/css/syntax-highlighting-github-style.css" rel="stylesheet"

Which makes it if later than IE 8, not realising that I can only target if later than IE 9.

I have merged this onto Dev. We need to test this again. Sorry for the muck around.

**Comment by luchia** [comment]
Can you please merge the latest to beta? Then I can test it with IE8.

**Comment by luchia** [comment]
Alright, I found our issue -

![screen shot 2015-09-24 at 7 21 07 am](https://cloud.githubusercontent.com/assets/4547737/10059247/42d21360-628d-11e5-93ec-af02c39875ec.png)
![screen shot 2015-09-24 at 7 20 48 am](https://cloud.githubusercontent.com/assets/4547737/10059246/42ca2c22-628d-11e5-8520-05f1f9157f87.png)

The conditional comment wasn't being rendered properly because of Jade. This has been merged into Dev, can we get TM_Jade into Beta so one of us can test it?

**Comment by luchia** [comment]
I'm really, really close with this. I just went through it and picked up a few small details that I missed. One thing that I've found is that the results showing and active filters aren't working in IE8

![screen shot 2015-09-26 at 12 58 07 pm](https://cloud.githubusercontent.com/assets/4547737/10115535/5cb3c464-644e-11e5-8cfa-640a6059e3b3.png)

I don't think this is a CSS issue.

I will submit my PR today and if you can reload the beta @roman87, I think we will be done today (for this specific issue).

**Comment by romichg** [comment]
I just reloaded tmdev01 5 min ago..

**Comment by romichg** [comment]
So couple of issues that I noticed with this
1. The number of results and the active filters are not showing (as you pointed above)
2. Some articles show metadata weirdly
![selection_002](https://cloud.githubusercontent.com/assets/1326120/10141174/096059e4-65d9-11e5-89d8-fb2d8f325617.png)
3. article titles scroll pass the search view
![selection_001](https://cloud.githubusercontent.com/assets/1326120/10141659/c9b7d094-65db-11e5-9461-d918db884eaf.png)
4. Weird X on the search box when searching
![selection_003](https://cloud.githubusercontent.com/assets/1326120/10141198/18c2f9be-65d9-11e5-95cb-0a0ab3c7d859.png)

**Comment by luchia** [comment]
1. Going to need help with this because I think it's to do with data/logic, not css/html. We have breadcrumbs, but no 'results showing' and active filters -

![screen shot 2015-09-29 at 10 01 23 am](https://cloud.githubusercontent.com/assets/4547737/10152033/153adbfa-6691-11e5-8b05-7373b8e30f52.png)
1. I wasn't able to recreate the issue you had on Saucelabs, but had another set of issues (which we discussed) regarding icons while emulating.

![screen shot 2015-09-29 at 9 59 35 am](https://cloud.githubusercontent.com/assets/4547737/10152016/e3f03018-6690-11e5-8886-2c97174fd156.png)
1. Fixed
2. [This SO question](http://stackoverflow.com/questions/17472998/how-to-remove-clear-button-from-ie7-9) says that we shouldn't have an issue because IE9 and prior don't actually have the clear input and the only reason we can see it is because we are emulating in a newer version of IE.

I think this is true because on Saucelabs there is no X -

![screen shot 2015-09-29 at 9 56 49 am](https://cloud.githubusercontent.com/assets/4547737/10151948/79a55120-6690-11e5-88b1-9f4ce2b4f211.png)

**Comment by romichg** [comment]
What about #1 above is that fixed?

**Comment by luchia** [comment]
Woops, no. Assigned to Michael.

**Comment by michaelhidalgo** [comment]
Ok, it seems like the problem is with the mobile class
![screen shot 2015-09-29 at 16 09 34](https://cloud.githubusercontent.com/assets/1732035/10179675/cc1dceb2-66c4-11e5-84a2-0fea44d4f2e3.png)
![screen shot 2015-09-29 at 16 07 22](https://cloud.githubusercontent.com/assets/1732035/10179676/cc1fee7c-66c4-11e5-9eb3-ca562513ad1b.png)
![screen shot 2015-09-29 at 16 05 41](https://cloud.githubusercontent.com/assets/1732035/10179677/cc2126e8-66c4-11e5-9aeb-9f1c2ca8a5e8.png)

**Comment by luchia** [comment]
Got it :) In my PR today

![screen shot 2015-09-30 at 8 23 35 am](https://cloud.githubusercontent.com/assets/4547737/10179940/bad108c6-674c-11e5-8b50-6dcfbf3b27ea.png)

**Comment by romichg** [comment]
This is now fixed.
