### ISSUE TITLE
Lib_UNO-Json should not be a submodule and should not be a repository

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#882]
1. It breaks the flow of 
   git checkout Dev
   git submodule init
   git submodule update
   Make changes and edits to Lib_UNO
   ./bin/reload-data.sh
   git submodule update
2. It is fully populated from Lib_UNO at the moment and is a transform,  therefore should not be its own repo. Should be populated from Lib_UNO at install time
3. For future, as we move towards storing things in json, we create a directory "json" inside Lib_UNO and store them there.

**Comment by DinisCruz** [comment]
That is true, since (apart from that virtual-articles.json file) it is all a transform. 

Only issue is that we need to do the full conversion the first time we do a git clone of TM, so the Lib_Uno-json acts like a cache.

Btw, note that on the steps you have above you still need to add and commit the changes to Lib_Uno, and since you are going to need to update the Lib_Uno submodule on TM, updating the Lib_Uno-json submodule is not that much more work (specially since in practice TM 4.0 only needs Lib-Uno-json  (i.e. it doesn't need Lib-UNO)

I don't have strong view on this one since this is more of a deployment/content-edit vs development issue

**Comment by romichg** [comment]
That is true, the problem occurs more when there are multiple content branches/forks like we have today. 
Ok I'll make the changes but they will depend on https://github.com/TeamMentor/TM_4_0_Design/issues/880

**Comment by roman87** [comment]
PR for removal here https://github.com/TeamMentor/TM/pull/9

**Comment by romichg** [comment]
PR for removal https://github.com/TeamMentor/TM/pull/10

**Comment by DinisCruz** [comment]
this is done right?
