### ISSUE TITLE
Weird sporadic caching issue in FF

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#910]
Start with a fresh (cache cleared) browser instance.
hit tmdev01-beta.teammentor.net
click on Docs
Click on Login, and login
Click on Docs again

As you can see, the "logged out" menu is displayed. Hitting the back button puts you back in the main page, and you are still logged in.
![selection_366](https://cloud.githubusercontent.com/assets/1326120/8920500/e58af62c-3497-11e5-9a82-8a1d6a6295e7.png)

**Comment by luchia** [comment]
Hmm, so the HTML templates that handle this seem to be okay and the problem isn't with what's being rendered. My guess would be that it's:
- The logic creating the functionality; or
- A caching issue.

When you refresh the docs page (the second time), you get the correct navbar. It's also not just FF that this does it in as I can get this in Chrome as well. These two factors make me think that it's a caching issue, more than anything else.

**Comment by romichg** [comment]
Hmm.. for some reason the response comes back as 304 when in fact it shouldn't. When you say caching issue, which cache you are talking about?

I was able to hit the docs page a couple of times and get the wrong navbar btw. Interesting that you can get in in Chrome. It seems sporadic, which is what bothers me.

**Comment by luchia** [comment]
I mean that the app caches the navbar, instead of reloading it. So the use case is:
- The app loads the docs page (when you're logged out) and it stores the navbar and page
- Then you login and load the same page again
- The app has already cached the page and reloads what it already has stored
- But, for some reason, the if/else statement that handles what a user sees when they are logged in vs logged out, is not triggering a reload of the navbar
- So you're seeing what you saw before you logged in, which I am assuming has to do with the application's cache.

This is a weird bug. I think I may need help from @DinisCruz or @michaelhidalgo, as the templates that display are fine, but it seems to be an issue of what the app is delivering to the browser.

**Comment by luchia** [comment]
Assigning to @michaelhidalgo as per our meeting tonight.

**Comment by romichg** [comment]
This is fixed. Great findings. Good work!
