### ISSUE TITLE
Wrong number of articles shown

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#922]
With current library on tmdev01-beta.teammentor.net 
Select Authentication, select Guideline Filter
The count shows 17 articles. However only 10 articles are shown. Jade shows correct 17 articles. 
![selection_396](https://cloud.githubusercontent.com/assets/1326120/9153466/20ea700c-3e26-11e5-803e-dba63098e283.png)

**Comment by romichg** [comment]
Some more issues here:
- [ ] 1. Search for XSS, select 4 articles per page, go to the last page (20), now select "Scala Play" this is what you get:
  ![selection_070](https://cloud.githubusercontent.com/assets/1326120/9925760/2e27354a-5cdd-11e5-9cd7-5c1aa2530ed4.png)
- [ ] 2. When there is 1 article left in a series (for example 77th article out of 77) we should say - SHOWING ARTICLE 77 out of 77, instead of what we say now 
  ![selection_069](https://cloud.githubusercontent.com/assets/1326120/9925764/34183a30-5cdd-11e5-8134-518e84e7e8d6.png)
- [ ] 3.  When there is only 1 article to show, we should say SHOWING 1 ARTICLE instead of SHOWING 1 ARTICLES

**Comment by michaelhidalgo** [comment]
Good catch @roman87, the problem seems to be that when you pickup a filter, it does not reset the pages dropdownlist, so if the filter has 10 articles and you are in page 20 of a previous search, it will do the wrong computation.

The solution here is to reset the pages to 1 when selecting a filter, so it starts from the first  page. I'm trying to fix it.

**Comment by michaelhidalgo** [comment]
With Pull Request

**Comment by romichg** [comment]
This looks good. Closing.
