### ISSUE TITLE
dingy of Flare issues (Lucy)

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#944]
- [x] Numbers next to the filters shoudl not be extra long on 2 lines (lucy)
- [x] breadcrumbs are not well visible (Dinis/Lucy)
- [x] maybe filters are too wide? (Lucy)
- [x] badges block first title (Lucy)
- [x] copyright message is missing at the end of each article (Lucy)
- [x] Single row box is too big (Lucy)
- [x] gray column next to article box changes size with single/double column of boxes (Lucy)
- [x] Overall font is to gray, strains my eyes(Lucy)
- [x] Share button shoudl show a popup with a link to the article, not mail (Lucy/Dinis)
- [x] Replace "RELATES TO" in full article view with "METADATA" (or simillar) We have enough space to also include text next to the icons. (Lucy)
- [x] Index will be the first page users see, we need another name/icon for the current home page. (Lucy)
- [x] Images are still huge in docs (Lucy)
- [x] Links are not underlined in docs (Lucy)

**Comment by luchia** [comment]
Here's some of my thoughts about the filters too wide checkpoint -

I think we should leave it as is because:
- It's balanced (design is symmetrical)

![screen shot 2015-08-25 at 10 17 41 am](https://cloud.githubusercontent.com/assets/4547737/9455834/a86b6876-4b12-11e5-85e6-f3dc283261bb.png)
- It's the same as Jade
- Making the column smaller means it gets really tight when the screen starts to scale down

I think condensing the way filters are displayed would be a better solution, rather than making the container smaller.

**Comment by luchia** [comment]
Finished the share modal, here's a screenshot. It's currently commented out.

![screen shot 2015-08-26 at 10 04 48 am](https://cloud.githubusercontent.com/assets/4547737/9482687/eeb72d52-4bd9-11e5-80dd-0f28e2ec1349.png)

Will push in a bit, still doing some other stuff.

**Comment by romichg** [comment]
@michaelhidalgo can you wire up the share modal?

**Comment by romichg** [comment]
All done or tracked elsewhere.
