### ISSUE TITLE
Animation during the selection of dropdown

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#999]
See @DinisCruz comment on slack https://securityinnovation.slack.com/archives/tmdev/p1442339213000997

**Comment by luchia** [comment]
Fixed in my PR today, see beta to see it in action -

![screen shot 2015-09-17 at 9 03 53 am](https://cloud.githubusercontent.com/assets/4547737/9920858/1ebc1bdc-5d1b-11e5-8380-28ac2f40b76e.png)
![screen shot 2015-09-17 at 9 03 56 am](https://cloud.githubusercontent.com/assets/4547737/9920859/1ebf28d6-5d1b-11e5-878b-c22df49d930d.png)
![screen shot 2015-09-17 at 9 03 59 am](https://cloud.githubusercontent.com/assets/4547737/9920860/1f1a6b92-5d1b-11e5-838c-c3abd51c74a4.png)

**Comment by romichg** [comment]
Animations are fixed. Still an issue with #969
